name = "SymmetryGraded"
version = "0.1.0"
defaultTargets = ["SymmetryGraded"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "SymmetryGraded"
