/-
  NormCriterion.lean

  Formal verification (Lean 4 + Mathlib) of the polynomial part of

    Lemma "Norm criterion"  (Appendix "Proofs for the framework")

  of "Symmetry-Graded Digit Extraction for Faster BGV/BFV Bootstrapping":
  a monic irreducible `F ∈ K[Y]` of degree `d = [L : K]` is the orbit product
  `Orb_d(Y − α) = ∏_{i<d} (Y − σⁱα)` of a linear factor over the degree-`d` extension
  `L`, and products of such factors are orbit products of products.  The extension
  `F_{p^d}/F_p` is modelled first abstractly — `L/K` a finite Galois extension whose
  Galois group is generated by one automorphism `σ` (the Frobenius) — and then
  concretely for finite fields, where `σ = FiniteField.frobeniusAlgEquivOfAlgebraic K L`
  (`x ↦ x^{|K|}`) and `d = finrank K L` (for `K = ZMod p`, `L = GaloisField p d`).
  With no unproved placeholders:

  * `conjProd`, `conjProd_eq_orbProd`
        `∏_{i<d} (Y − σⁱα)` equals `Galois.orbProd (mapRingHom σ) d (Y − α)`.
  * `conjProd_map_eq`, `conjProd_lifts`
        the conjugate product is `σ`-fixed, hence has coefficients in `K`
        (fixed field of the full Galois group is `K`).
  * `minpoly_map_eq_conjProd`
        if `deg minpoly_K(α) = d` then `minpoly_K(α) = ∏_{i<d} (Y − σⁱα)` over `L`.
  * `exists_root_of_irreducible` (finite fields)
        an irreducible `F ∈ K[Y]` of degree `d = [L : K]` has a root in `L`.
  * `irreducible_eq_orbProd` (Lemma "Norm criterion", irreducible case)
        `F` monic irreducible of degree `d` ⟹ `F = Orb_d(Y − α)` over `L`.
  * `orbProd_mul`, `orbProd_prod`, `orbProd_of_fixed`
        multiplicativity of `Orb_d`, and `Orb_d(g) = g^d` for `σ`-fixed `g`.
  * `norm_form_of_factors`, `prod_irreducible_eq_orbProd`
        (Lemma "Norm criterion", ⇐ for products of degree-`d` irreducibles)
        `F = ∏ h_i` with each `h_i` monic irreducible of degree `d` ⟹
        `F = Orb_d(C)` with `C = ∏ (Y − α_i)` monic of degree `deg F / d`.
  * `orbit_full_of_separable_orbProd`, `minpoly_natDegree_eq_of_orbit_full`,
    `natDegree_eq_finrank_of_squarefree_orbProd`, `factor_natDegree_eq_finrank_of_squarefree_orbProd`
        (Lemma "Norm criterion", ⇒ for squarefree `F`, factors with a root in `L`)
        if `F` is squarefree and `F = Orb_d(C)` over `L`, then no root `β ∈ L` of `F`
        is fixed by a proper power of `σ`, so `deg minpoly_K(β) = d`; every irreducible
        factor `h` of `F` having a root in `L` has degree exactly `d`.
  * `irreducible_eq_orbProd_galoisField`, `prod_irreducible_eq_orbProd_galoisField`
        the concrete instance `K = ZMod p`, `L = GaloisField p d`.

  * `orbProd_monic`, `natDegree_orbProd_of_monic`, `orbProd_lifts`, `dvd_orbProd_self`
        (round 4) `Orb_d(C)` of a monic `C` is monic of degree `d·deg C`, is `σ`-fixed,
        hence has coefficients in `K`; `C ∣ Orb_d(C)`.
  * `irreducible_eq_orbProd_of_tower`, `prod_irreducible_eq_orbProd_of_tower`
        (round 4; Lemma "Norm criterion", sufficiency for `d ∣ deg h`)
        for a tower of finite fields `K ⊆ L ⊆ M` with `d = [L : K]`, `k = [M : L]`, a monic
        irreducible `h ∈ K[Y]` of degree `kd` is `Orb_d(C)` over `L` with `C = minpoly_L(β)`
        monic of degree `k` (`β ∈ M` a root of `h`): `h` splits over `L` into the `d`
        Frobenius conjugates of `C`; products of such factors likewise.
  * `irreducible_eq_orbProd_galoisField_of_dvd`, `prod_irreducible_eq_orbProd_galoisField_of_dvd`
        the concrete instance `K = ZMod p`, `L = GaloisField p d`, `M = GaloisField p (kd)`.

  * (round 5, sections 9–12) the **general multiplicity criterion**:
    `period`, `map_eq_orbProd_period` (`h = Orb_t(h₁)`, `deg h = t·deg h₁` for a monic
    irreducible factor `h₁` of `h` over `L` with Frobenius period `t`),
    `orbProd_eq_map_pow` (`Orb_d(h₁) = h^{d/t}`), `pow_eq_orbProd_of_dvd` (sufficiency:
    `d/t ∣ μ ⟹ h^μ = Orb_d(h₁^{μt/d})`), `emultiplicity_orbProd`,
    `period_div_dvd_of_orbProd`, `dvd_natDegree_mul_of_orbProd` (necessity for
    non-squarefree `F`: `h^μ ∥ F = Orb_d(C) ⟹ d/t ∣ μ`, hence `d ∣ m_h μ`),
    `minpoly_map_eq_conjProd_finite` (roots of a minimal polynomial over a finite field are
    the Frobenius conjugates, pairwise distinct), `period_eq_gcd_of_tower`,
    `period_eq_gcd_galoisField` (**`t = gcd(m_h, d)`**), `pow_eq_orbProd_galoisField_iff`
    (`h^μ` is a norm form over `F_{p^d}` ⟺ `d ∣ m_h μ`), `normForm_iff_galoisField`
    (`∏ hᵢ^{μᵢ}` is a norm form ⟺ `∀ i, d ∣ mᵢ μᵢ`), `normForm_of_dvd_galoisField`
    (`deg C = Σ mᵢ μᵢ / d`).

  Not formalized: the Hensel lift to `GR(p^e, d)`.
-/
import Mathlib
import SymmetryGraded.Doubling
import SymmetryGraded.Obstruction

namespace NormCriterion

open Polynomial

/-! ## 1. Multiplicativity of orbit products (any commutative ring) -/
section Mult
variable {R : Type*} [CommRing R]

/-- `Orb_d(x·y) = Orb_d(x)·Orb_d(y)`. -/
theorem orbProd_mul (φ : R →+* R) (d : ℕ) (x y : R) :
    Galois.orbProd φ d (x * y) = Galois.orbProd φ d x * Galois.orbProd φ d y := by
  unfold Galois.orbProd
  rw [← Finset.prod_mul_distrib]
  exact Finset.prod_congr rfl (fun i _ => map_mul _ _ _)

/-- `Orb_d(∏ᵢ xᵢ) = ∏ᵢ Orb_d(xᵢ)`. -/
theorem orbProd_prod (φ : R →+* R) (d : ℕ) {ι : Type*} (s : Finset ι) (x : ι → R) :
    Galois.orbProd φ d (∏ i ∈ s, x i) = ∏ i ∈ s, Galois.orbProd φ d (x i) := by
  unfold Galois.orbProd
  rw [Finset.prod_comm]
  exact Finset.prod_congr rfl (fun i _ => map_prod _ _ _)

/-- `Orb_d(g) = g^d` for a `φ`-fixed element `g` (a base-ring polynomial). -/
theorem orbProd_of_fixed (φ : R →+* R) (d : ℕ) {g : R} (hg : φ g = g) :
    Galois.orbProd φ d g = g ^ d := by
  unfold Galois.orbProd
  rw [Finset.prod_congr rfl (fun i _ => (show (φ ^ i) g = g by
    rw [RingHom.coe_pow]; exact Function.iterate_fixed hg i)), Finset.prod_const,
    Finset.card_range]

end Mult

/-! ## 2. The abstract setting: a cyclic Galois extension `L/K` generated by `σ` -/
section Abstract
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The conjugate product `∏_{i<d} (Y − σⁱ α)`. -/
noncomputable def conjProd (σ : L ≃ₐ[K] L) (d : ℕ) (α : L) : L[X] :=
  ∏ i ∈ Finset.range d, (X - C ((σ ^ i) α))

/-- The ring endomorphism of `L` underlying `σ`. -/
def toHom (σ : L ≃ₐ[K] L) : L →+* L := RingHomClass.toRingHom σ

@[simp] lemma toHom_apply (σ : L ≃ₐ[K] L) (x : L) : toHom σ x = σ x := rfl

lemma toHom_pow_apply (σ : L ≃ₐ[K] L) (i : ℕ) (x : L) : (toHom σ ^ i) x = (σ ^ i) x := by
  rw [RingHom.coe_pow, AlgEquiv.coe_pow]; rfl

/-- The conjugate product is the orbit product `Orb_d(Y − α)` of `Doubling.lean`. -/
theorem conjProd_eq_orbProd (σ : L ≃ₐ[K] L) (d : ℕ) (α : L) :
    conjProd σ d α = Galois.orbProd (mapRingHom (toHom σ)) d (X - C α) := by
  unfold conjProd Galois.orbProd
  apply Finset.prod_congr rfl
  intro i _
  rw [Galois.mapRingHom_pow, coe_mapRingHom, Polynomial.map_sub, map_X, map_C, toHom_pow_apply]

theorem conjProd_monic (σ : L ≃ₐ[K] L) (d : ℕ) (α : L) : (conjProd σ d α).Monic :=
  monic_prod_of_monic _ _ (fun _ _ => monic_X_sub_C _)

theorem conjProd_natDegree (σ : L ≃ₐ[K] L) (d : ℕ) (α : L) :
    (conjProd σ d α).natDegree = d := by
  unfold conjProd
  rw [natDegree_prod_of_monic _ _ (fun i _ => monic_X_sub_C _)]
  simp

theorem conjProd_ne_zero (σ : L ≃ₐ[K] L) (d : ℕ) (α : L) : conjProd σ d α ≠ 0 :=
  (conjProd_monic σ d α).ne_zero

/-- `α` is a root of its conjugate product (`d ≥ 1`). -/
theorem eval_conjProd (σ : L ≃ₐ[K] L) {d : ℕ} (hd : 0 < d) (α : L) :
    (conjProd σ d α).eval α = 0 := by
  unfold conjProd
  rw [eval_prod, Finset.prod_eq_zero_iff]
  exact ⟨0, Finset.mem_range.mpr hd, by simp⟩

/-- The conjugate product is `σ`-fixed when `σ^d = 1` (cyclic reindexing). -/
theorem conjProd_map_eq (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1) (α : L) :
    (conjProd σ d α).map (toHom σ) = conjProd σ d α := by
  unfold conjProd
  rw [Polynomial.map_prod]
  have h1 : ∀ i, (X - C ((σ ^ i) α)).map (toHom σ) = X - C ((σ ^ (i + 1)) α) := by
    intro i
    rw [Polynomial.map_sub, map_X, map_C, toHom_apply, pow_succ', AlgEquiv.mul_apply]
  simp_rw [h1]
  have h2 : ((σ ^ d) α) = (σ ^ 0) α := by rw [hσ, pow_zero]
  have hA := Finset.prod_range_succ (fun i => (X - C ((σ ^ i) α) : L[X])) d
  have hB := Finset.prod_range_succ' (fun i => (X - C ((σ ^ i) α) : L[X])) d
  rw [hA, h2] at hB
  exact mul_right_cancel₀ (X_sub_C_ne_zero _) hB.symm

variable [FiniteDimensional K L] [IsGalois K L]

/-- An element fixed by every automorphism lies in the base field (`fixedField ⊤ = ⊥`). -/
theorem mem_range_algebraMap_of_fixed {x : L} (hx : ∀ τ : L ≃ₐ[K] L, τ x = x) :
    x ∈ Set.range (algebraMap K L) := by
  rw [← IntermediateField.mem_bot, ← IsGalois.fixedField_top, IntermediateField.mem_fixedField_iff]
  intro τ _; exact hx τ

/-- If `σ` generates the Galois group, an element fixed by `σ` lies in `K`. -/
theorem mem_range_algebraMap_of_fixed_gen (σ : L ≃ₐ[K] L)
    (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ) {x : L} (hx : σ x = x) :
    x ∈ Set.range (algebraMap K L) := by
  apply mem_range_algebraMap_of_fixed
  intro τ
  obtain ⟨i, rfl⟩ := hgen τ
  rw [AlgEquiv.coe_pow]; exact Function.iterate_fixed hx i

/-- The conjugate product has coefficients in `K`: it is `g.map (algebraMap K L)` for a
    monic `g ∈ K[Y]` of degree `d`. -/
theorem conjProd_lifts (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hσ : σ ^ d = 1) (α : L) :
    ∃ g : K[X], g.map (algebraMap K L) = conjProd σ d α ∧ g.natDegree = d ∧ g.Monic := by
  have hl : conjProd σ d α ∈ lifts (algebraMap K L) := by
    rw [lifts_iff_coeff_lifts]
    intro n
    apply mem_range_algebraMap_of_fixed_gen σ hgen
    have := congrArg (fun p : L[X] => p.coeff n) (conjProd_map_eq σ hσ α)
    simpa [coeff_map] using this
  obtain ⟨g, hg, hdeg, hmon⟩ := lifts_and_natDegree_eq_and_monic hl (conjProd_monic σ d α)
  exact ⟨g, hg, hdeg.trans (conjProd_natDegree σ d α), hmon⟩

/-- If the minimal polynomial of `α` has degree `d` (`α` generates `L`), then over `L`
    it is the conjugate product `∏_{i<d} (Y − σⁱ α)`. -/
theorem minpoly_map_eq_conjProd (σ : L ≃ₐ[K] L)
    (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ) {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    (α : L) (hdeg : (minpoly K α).natDegree = d) :
    (minpoly K α).map (algebraMap K L) = conjProd σ d α := by
  obtain ⟨g, hg, hgdeg, hgmon⟩ := conjProd_lifts σ hgen hσ α
  have hroot : aeval α g = 0 := by
    rw [aeval_def, ← eval_map, hg]; exact eval_conjProd σ hd α
  have hdvd : minpoly K α ∣ g := minpoly.dvd K α hroot
  have hmin : (minpoly K α).Monic := minpoly.monic (IsIntegral.of_finite K α)
  have heq : minpoly K α = g := by
    apply eq_of_monic_of_associated hmin hgmon
    obtain ⟨q, hq⟩ := hdvd
    have hq0 : q ≠ 0 := by rintro rfl; rw [mul_zero] at hq; exact hgmon.ne_zero hq
    have hdq : q.natDegree = 0 := by
      have := congrArg natDegree hq
      rw [natDegree_mul hmin.ne_zero hq0, hdeg, hgdeg] at this
      omega
    rw [hq]
    apply associated_mul_unit_right
    rw [isUnit_iff_degree_eq_zero, degree_eq_natDegree hq0, hdq]
    rfl
  rw [heq, hg]

end Abstract

/-! ## 3. Finite fields: `σ` the Frobenius, `d = [L : K]` -/
section FiniteField
variable {K L : Type*} [Field K] [Fintype K] [Field L] [Algebra K L] [Finite L]

/-- The Frobenius `x ↦ x^{|K|}` as a `K`-automorphism of `L`. -/
noncomputable def frob : L ≃ₐ[K] L :=
  FiniteField.frobeniusAlgEquivOfAlgebraic K L

theorem frob_apply (x : L) : (frob : L ≃ₐ[K] L) x = x ^ Fintype.card K := rfl

/-- `σ^d = 1` for `d = [L : K]`. -/
theorem frob_pow_finrank : (frob : L ≃ₐ[K] L) ^ Module.finrank K L = 1 := by
  have := FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic K L
  rw [← this]; exact pow_orderOf_eq_one _

/-- The Frobenius generates the Galois group. -/
theorem frob_gen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, (frob : L ≃ₐ[K] L) ^ i = τ := by
  intro τ
  obtain ⟨⟨i, _⟩, hi⟩ := (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow K L).2 τ
  exact ⟨i, hi⟩

omit [Fintype K] in
/-- An irreducible polynomial of degree `[L : K]` over a finite field `K` has a root in
    the extension `L` (uniqueness of the field with `|K|^d` elements). -/
theorem exists_root_of_irreducible (F : K[X]) (hF : Irreducible F)
    (hd : F.natDegree = Module.finrank K L) : ∃ α : L, aeval α F = 0 := by
  haveI : Fact (Irreducible F) := ⟨hF⟩
  have hF0 : F ≠ 0 := hF.ne_zero
  have hfin : Module.finrank K (AdjoinRoot F) = F.natDegree := by
    rw [(AdjoinRoot.powerBasis hF0).finrank, AdjoinRoot.powerBasis_dim]
  obtain ⟨f⟩ := FiniteField.nonempty_algHom_of_finrank_dvd (F := K) (K := AdjoinRoot F) (L := L)
    (by rw [hfin, hd])
  refine ⟨f (AdjoinRoot.root F), ?_⟩
  rw [aeval_algHom_apply, AdjoinRoot.aeval_eq, AdjoinRoot.mk_self, map_zero]

/-- (Lemma "Norm criterion", irreducible case.)  A monic irreducible `F ∈ K[Y]` of degree
    `d = [L : K]` is the orbit product of a linear factor over `L`:
    `F = ∏_{i<d} (Y − σⁱ α) = Orb_d(Y − α)` for a root `α ∈ L`. -/
theorem irreducible_eq_orbProd (F : K[X]) (hF : Irreducible F) (hmon : F.Monic)
    (hd : F.natDegree = Module.finrank K L) :
    ∃ α : L, aeval α F = 0 ∧
      F.map (algebraMap K L) = conjProd (frob : L ≃ₐ[K] L) (Module.finrank K L) α ∧
      F.map (algebraMap K L) =
        Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) (X - C α) := by
  obtain ⟨α, hα⟩ := exists_root_of_irreducible (L := L) F hF hd
  have hmin : F = minpoly K α := minpoly.eq_of_irreducible_of_monic hF hα hmon
  have h := minpoly_map_eq_conjProd (frob : L ≃ₐ[K] L) frob_gen Module.finrank_pos
    frob_pow_finrank α (by rw [← hmin, hd])
  rw [← hmin] at h
  exact ⟨α, hα, h, h.trans (conjProd_eq_orbProd _ _ _)⟩

end FiniteField

/-! ## 4. Products of factors -/
section Products
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- If every factor `h i` is an orbit product `Orb_d(C i)` over `L`, so is the product:
    `(∏ h i).map = Orb_d(∏ C i)`. -/
theorem norm_form_of_factors (π : L[X] →+* L[X]) (d : ℕ) {ι : Type*} (s : Finset ι)
    (h : ι → K[X]) (Cf : ι → L[X])
    (hh : ∀ i ∈ s, (h i).map (algebraMap K L) = Galois.orbProd π d (Cf i)) :
    (∏ i ∈ s, h i).map (algebraMap K L) = Galois.orbProd π d (∏ i ∈ s, Cf i) := by
  rw [Polynomial.map_prod, orbProd_prod]
  exact Finset.prod_congr rfl hh

variable [Fintype K] [Finite L]

/-- (Lemma "Norm criterion", ⇐ for a product of degree-`d` irreducibles.)  If
    `F = ∏_{i∈s} h i` with every `h i` monic irreducible of degree `d = [L : K]`, then
    `F = Orb_d(C)` over `L` with `C = ∏ (Y − αᵢ)` monic of degree `|s| = deg F / d`. -/
theorem prod_irreducible_eq_orbProd {ι : Type*} (s : Finset ι) (h : ι → K[X])
    (hirr : ∀ i ∈ s, Irreducible (h i)) (hmon : ∀ i ∈ s, (h i).Monic)
    (hdeg : ∀ i ∈ s, (h i).natDegree = Module.finrank K L) :
    ∃ Cp : L[X], Cp.Monic ∧ Cp.natDegree = s.card ∧
      (∏ i ∈ s, h i).map (algebraMap K L) =
        Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) Cp := by
  classical
  choose! α hα using fun i (hi : i ∈ s) => irreducible_eq_orbProd (L := L) (h i) (hirr i hi)
    (hmon i hi) (hdeg i hi)
  refine ⟨∏ i ∈ s, (X - C (α i)), monic_prod_of_monic _ _ (fun i _ => monic_X_sub_C _), ?_, ?_⟩
  · rw [natDegree_prod_of_monic _ _ (fun i _ => monic_X_sub_C _)]
    simp
  · exact norm_form_of_factors _ _ s h _ (fun i hi => (hα i hi).2.2)

end Products

/-! ## 5. Necessity for squarefree `F`: roots of an orbit product have full orbits -/
section Necessity
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Evaluation of a `σ`-twisted polynomial: `(σf)(σx) = σ(f(x))`. -/
lemma eval_map_toHom (σ : L ≃ₐ[K] L) (f : L[X]) (x : L) :
    (f.map (toHom σ)).eval (σ x) = σ (f.eval x) := by
  rw [eval_map]; exact eval₂_at_apply (toHom σ) x

/-- Some conjugate `σ^{j} C` vanishes at every root `β` of `Orb_d(C)`. -/
lemma exists_conj_root (σ : L ≃ₐ[K] L) (d : ℕ) (Cp : L[X]) {β : L}
    (hβ : (Galois.orbProd (mapRingHom (toHom σ)) d Cp).eval β = 0) :
    ∃ j ∈ Finset.range d, (Cp.map (toHom σ ^ j)).eval β = 0 := by
  unfold Galois.orbProd at hβ
  rw [eval_prod, Finset.prod_eq_zero_iff] at hβ
  obtain ⟨j, hj, hj0⟩ := hβ
  refine ⟨j, hj, ?_⟩
  rwa [Galois.mapRingHom_pow, coe_mapRingHom] at hj0

/-- If `σ^j C` vanishes at `β` then `σ^{j+i} C` vanishes at `σ^i β`. -/
lemma conj_root_shift (σ : L ≃ₐ[K] L) (Cp : L[X]) {β : L} (j i : ℕ)
    (h : (Cp.map (toHom σ ^ j)).eval β = 0) :
    (Cp.map (toHom σ ^ (j + i))).eval ((σ ^ i) β) = 0 := by
  induction i with
  | zero => simpa using h
  | succ i ih =>
      have e1 : toHom σ ^ (j + (i + 1)) = toHom σ * toHom σ ^ (j + i) := by
        rw [← add_assoc, pow_succ']
      have e2 : (σ ^ (i + 1)) β = σ ((σ ^ i) β) := by rw [pow_succ', AlgEquiv.mul_apply]
      rw [e1, e2, RingHom.mul_def, ← Polynomial.map_map, eval_map_toHom, ih, map_zero]

/-- Two distinct conjugates vanishing at `β` give `(Y − β)² ∣ Orb_d(C)`. -/
lemma sq_dvd_orbProd_of_two_roots (σ : L ≃ₐ[K] L) (d : ℕ) (Cp : L[X]) {β : L}
    {j₁ j₂ : ℕ} (h1 : j₁ ∈ Finset.range d) (h2 : j₂ ∈ Finset.range d) (hne : j₁ ≠ j₂)
    (r1 : (Cp.map (toHom σ ^ j₁)).eval β = 0) (r2 : (Cp.map (toHom σ ^ j₂)).eval β = 0) :
    (X - C β) ^ 2 ∣ Galois.orbProd (mapRingHom (toHom σ)) d Cp := by
  classical
  unfold Galois.orbProd
  have hf : ∀ j, ((mapRingHom (toHom σ)) ^ j) Cp = Cp.map (toHom σ ^ j) := by
    intro j; rw [Galois.mapRingHom_pow, coe_mapRingHom]
  rw [← Finset.mul_prod_erase _ _ h1,
    ← Finset.mul_prod_erase _ _ (Finset.mem_erase.mpr ⟨hne.symm, h2⟩), ← mul_assoc, pow_two]
  apply Dvd.dvd.mul_right
  apply mul_dvd_mul
  · rw [hf, dvd_iff_isRoot]; exact r1
  · rw [hf, dvd_iff_isRoot]; exact r2

/-- (Lemma "Norm criterion", ⇒ for squarefree `F`, orbit form.)  If `F ∈ K[Y]` is
    separable and `F = Orb_d(C)` over `L` with `σ^d = 1`, then no root `β ∈ L` of `F` is
    fixed by a proper power `σ^i`, `0 < i < d`: the `σ`-orbit of `β` has exactly `d`
    elements. -/
theorem orbit_full_of_separable_orbProd (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1)
    {F : K[X]} (hsep : F.Separable) {Cp : L[X]}
    (hF : F.map (algebraMap K L) = Galois.orbProd (mapRingHom (toHom σ)) d Cp)
    {β : L} (hβ : aeval β F = 0) : ∀ i, 0 < i → i < d → (σ ^ i) β ≠ β := by
  intro i hi0 hid hfix
  have hβ' : (Galois.orbProd (mapRingHom (toHom σ)) d Cp).eval β = 0 := by
    rw [← hF, eval_map, ← aeval_def]; exact hβ
  obtain ⟨j, hj, hj0⟩ := exists_conj_root σ d Cp hβ'
  have hshift := conj_root_shift σ Cp j i hj0
  rw [hfix] at hshift
  have hmod : toHom σ ^ (j + i) = toHom σ ^ ((j + i) % d) := by
    have : toHom σ ^ d = 1 := by
      ext x; rw [toHom_pow_apply, hσ]; rfl
    exact pow_eq_pow_mod _ this
  rw [hmod] at hshift
  have hjd : j < d := Finset.mem_range.mp hj
  have hne : j ≠ (j + i) % d := by
    intro h
    by_cases hlt : j + i < d
    · rw [Nat.mod_eq_of_lt hlt] at h; omega
    · have : (j + i) % d = j + i - d := by
        rw [Nat.mod_eq_sub_mod (by omega), Nat.mod_eq_of_lt (by omega)]
      omega
  have hdvd := sq_dvd_orbProd_of_two_roots σ d Cp hj
    (Finset.mem_range.mpr (Nat.mod_lt _ (by omega))) hne hj0 hshift
  rw [← hF] at hdvd
  have hF0 : F.map (algebraMap K L) ≠ 0 :=
    (Polynomial.map_ne_zero_iff (algebraMap K L).injective).mpr hsep.ne_zero
  have h2 : 2 ≤ (F.map (algebraMap K L)).rootMultiplicity β :=
    (le_rootMultiplicity_iff hF0).mpr hdvd
  have h1 := rootMultiplicity_le_one_of_separable (hsep.map (f := algebraMap K L)) β
  omega

variable [FiniteDimensional K L] [IsGalois K L]

/-- `d` distinct conjugates force `deg minpoly_K(β) = d` when `d = [L : K]`. -/
theorem minpoly_natDegree_eq_of_orbit_full (σ : L ≃ₐ[K] L)
    (hd : Module.finrank K L = orderOf σ) {β : L}
    (hfull : ∀ i, 0 < i → i < orderOf σ → (σ ^ i) β ≠ β) :
    (minpoly K β).natDegree = Module.finrank K L := by
  classical
  set d := orderOf σ with hd'
  apply le_antisymm (minpoly.natDegree_le β)
  rw [hd]
  -- the `d` conjugates `σⁱβ`, `i < d`, are distinct roots of `minpoly K β` over `L`
  have hinj : Set.InjOn (fun i : ℕ => (σ ^ i) β) (Finset.range d : Set ℕ) := by
    intro i hi j hj hij
    simp only [Finset.coe_range, Set.mem_Iio] at hi hj
    by_contra hne
    rcases Nat.lt_or_gt_of_ne hne with h | h
    · apply hfull (j - i) (by omega) (by omega)
      have : (σ ^ j) β = (σ ^ i) ((σ ^ (j - i)) β) := by
        rw [← AlgEquiv.mul_apply, ← pow_add, Nat.add_sub_cancel' h.le]
      exact (σ ^ i).injective (by rw [← this]; exact hij.symm)
    · apply hfull (i - j) (by omega) (by omega)
      have : (σ ^ i) β = (σ ^ j) ((σ ^ (i - j)) β) := by
        rw [← AlgEquiv.mul_apply, ← pow_add, Nat.add_sub_cancel' h.le]
      exact (σ ^ j).injective (by rw [← this]; exact hij)
  have hcard : ((Finset.range d).image (fun i : ℕ => (σ ^ i) β)).card = d := by
    rw [Finset.card_image_of_injOn hinj, Finset.card_range]
  have hmap0 : (minpoly K β).map (algebraMap K L) ≠ 0 :=
    (Polynomial.map_ne_zero_iff (algebraMap K L).injective).mpr
      (minpoly.ne_zero (IsIntegral.of_finite K β))
  calc d = ((Finset.range d).image (fun i : ℕ => (σ ^ i) β)).card := hcard.symm
    _ ≤ ((minpoly K β).map (algebraMap K L)).natDegree := by
        apply card_le_degree_of_subset_roots
        intro x hx
        rw [Finset.mem_val, Finset.mem_image] at hx
        obtain ⟨i, _, rfl⟩ := hx
        rw [mem_roots hmap0, IsRoot.def, eval_map, ← aeval_def, aeval_algHom_apply,
          minpoly.aeval, map_zero]
    _ = (minpoly K β).natDegree := natDegree_map _

end Necessity

/-! ## 6. Finite fields: the squarefree necessity for factors with a root in `L` -/
section NecessityFinite
variable {K L : Type*} [Field K] [Fintype K] [Field L] [Algebra K L] [Finite L]

theorem orderOf_frob : orderOf (frob : L ≃ₐ[K] L) = Module.finrank K L :=
  FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic K L

/-- (Lemma "Norm criterion", ⇒ for squarefree `F`, factors with a root in `L`.)
    Over a finite field `K` with `d = [L : K]`: if `F ∈ K[Y]` is squarefree and
    `F = Orb_d(C)` over `L` (Frobenius orbit product), then every root `β ∈ L` of `F`
    has `deg minpoly_K(β) = d`; hence every irreducible factor `h` of `F` that has a
    root in `L` has degree exactly `d`. -/
theorem natDegree_eq_finrank_of_squarefree_orbProd {F : K[X]} (hsq : Squarefree F)
    {Cp : L[X]}
    (hF : F.map (algebraMap K L) =
      Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) Cp)
    {β : L} (hβ : aeval β F = 0) :
    (minpoly K β).natDegree = Module.finrank K L := by
  have hsep : F.Separable := PerfectField.separable_iff_squarefree.mpr hsq
  have hfull := orbit_full_of_separable_orbProd (frob : L ≃ₐ[K] L) frob_pow_finrank hsep hF hβ
  rw [← orderOf_frob (K := K) (L := L)] at hfull
  exact minpoly_natDegree_eq_of_orbit_full _ orderOf_frob.symm hfull

/-- Irreducible-factor form: if `h ∣ F` is monic irreducible with a root `β ∈ L`, then
    `deg h = d`. -/
theorem factor_natDegree_eq_finrank_of_squarefree_orbProd {F : K[X]} (hsq : Squarefree F)
    {Cp : L[X]}
    (hF : F.map (algebraMap K L) =
      Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) Cp)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic) (hdvd : h ∣ F) {β : L}
    (hβ : aeval β h = 0) : h.natDegree = Module.finrank K L := by
  have hβF : aeval β F = 0 := by
    obtain ⟨q, rfl⟩ := hdvd; rw [map_mul, hβ, zero_mul]
  rw [minpoly.eq_of_irreducible_of_monic hirr hβ hmon]
  exact natDegree_eq_finrank_of_squarefree_orbProd hsq hF hβF

end NecessityFinite

/-! ## 7. The concrete instance `K = ZMod p`, `L = GaloisField p d` -/
section GaloisFieldInstance
variable (p : ℕ) [Fact p.Prime] (d : ℕ)

/-- `[GaloisField p d : ZMod p] = d` (`d ≠ 0`). -/
theorem finrank_galoisField (hd : d ≠ 0) :
    Module.finrank (ZMod p) (GaloisField p d) = d := GaloisField.finrank p hd

/-- (Lemma "Norm criterion", irreducible case, over `F_p`.)  A monic irreducible
    `F ∈ F_p[Y]` of degree `d ≥ 1` is `Orb_d(Y − α)` for a root `α ∈ F_{p^d}`. -/
theorem irreducible_eq_orbProd_galoisField (hd : d ≠ 0) (F : (ZMod p)[X])
    (hF : Irreducible F) (hmon : F.Monic) (hdeg : F.natDegree = d) :
    ∃ α : GaloisField p d, aeval α F = 0 ∧
      F.map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
          d (X - C α) := by
  obtain ⟨α, hα, -, h⟩ := irreducible_eq_orbProd (L := GaloisField p d) F hF hmon
    (by rw [hdeg, finrank_galoisField p d hd])
  refine ⟨α, hα, ?_⟩
  rw [h, finrank_galoisField p d hd]

/-- (Lemma "Norm criterion", ⇐ over `F_p` for a product of degree-`d` irreducibles.) -/
theorem prod_irreducible_eq_orbProd_galoisField (hd : d ≠ 0) {ι : Type*} (s : Finset ι)
    (h : ι → (ZMod p)[X]) (hirr : ∀ i ∈ s, Irreducible (h i)) (hmon : ∀ i ∈ s, (h i).Monic)
    (hdeg : ∀ i ∈ s, (h i).natDegree = d) :
    ∃ Cp : (GaloisField p d)[X], Cp.Monic ∧ Cp.natDegree = s.card ∧
      (∏ i ∈ s, h i).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
          d Cp := by
  obtain ⟨Cp, hCm, hCd, hC⟩ := prod_irreducible_eq_orbProd (L := GaloisField p d) s h hirr hmon
    (fun i hi => by rw [hdeg i hi, finrank_galoisField p d hd])
  refine ⟨Cp, hCm, hCd, ?_⟩
  rw [hC, finrank_galoisField p d hd]

/-- (Lemma "Norm criterion", ⇒ over `F_p`.)  For squarefree `F = Orb_d(C)` over `F_{p^d}`,
    every irreducible factor of `F` with a root in `F_{p^d}` has degree `d`. -/
theorem factor_natDegree_eq_galoisField (hd : d ≠ 0) {F : (ZMod p)[X]} (hsq : Squarefree F)
    {Cp : (GaloisField p d)[X]}
    (hF : F.map (algebraMap (ZMod p) (GaloisField p d)) =
      Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
        d Cp)
    {h : (ZMod p)[X]} (hirr : Irreducible h) (hmon : h.Monic) (hdvd : h ∣ F)
    {β : GaloisField p d} (hβ : aeval β h = 0) : h.natDegree = d := by
  have hfr := finrank_galoisField p d hd
  have hF' : F.map (algebraMap (ZMod p) (GaloisField p d)) =
      Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
        (Module.finrank (ZMod p) (GaloisField p d)) Cp := by
    rw [hF]; congr 1; exact hfr.symm
  rw [← hfr]
  exact factor_natDegree_eq_finrank_of_squarefree_orbProd hsq hF' hirr hmon hdvd hβ

end GaloisFieldInstance

/-! ## 8. Sufficiency for irreducible factors of degree `kd` -/
section DegreeKD
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- `Orb_d(C)` is monic when `C` is. -/
theorem orbProd_monic (σ : L ≃ₐ[K] L) (d : ℕ) {Cp : L[X]} (hC : Cp.Monic) :
    (Galois.orbProd (mapRingHom (toHom σ)) d Cp).Monic := by
  unfold Galois.orbProd
  apply monic_prod_of_monic
  intro i _
  rw [Galois.mapRingHom_pow, coe_mapRingHom]
  exact hC.map _

/-- `deg Orb_d(C) = d · deg C` for monic `C`. -/
theorem natDegree_orbProd_of_monic (σ : L ≃ₐ[K] L) (d : ℕ) {Cp : L[X]} (hC : Cp.Monic) :
    (Galois.orbProd (mapRingHom (toHom σ)) d Cp).natDegree = d * Cp.natDegree := by
  unfold Galois.orbProd
  rw [natDegree_prod_of_monic _ _ (fun i _ => by
    rw [Galois.mapRingHom_pow, coe_mapRingHom]; exact hC.map _)]
  simp only [Galois.mapRingHom_pow, coe_mapRingHom, hC.natDegree_map, Finset.sum_const,
    Finset.card_range, smul_eq_mul]

/-- `(toHom σ)^d = 1` when `σ^d = 1`. -/
theorem toHom_pow_eq_one (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1) : toHom σ ^ d = 1 := by
  ext x; rw [toHom_pow_apply, hσ]; rfl

/-- `C` divides `Orb_d(C)` for `d ≥ 1` (the `i = 0` factor). -/
theorem dvd_orbProd_self (σ : L ≃ₐ[K] L) {d : ℕ} (hd : 0 < d) (Cp : L[X]) :
    Cp ∣ Galois.orbProd (mapRingHom (toHom σ)) d Cp := by
  unfold Galois.orbProd
  have := Finset.dvd_prod_of_mem (fun i => ((mapRingHom (toHom σ)) ^ i) Cp)
    (Finset.mem_range.mpr hd)
  simpa using this

variable [FiniteDimensional K L] [IsGalois K L]

/-- For `σ` generating the Galois group with `σ^d = 1`, the orbit product of a monic `C`
    has coefficients in `K`. -/
theorem orbProd_lifts (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hσ : σ ^ d = 1) {Cp : L[X]} (hC : Cp.Monic) :
    ∃ g : K[X], g.map (algebraMap K L) = Galois.orbProd (mapRingHom (toHom σ)) d Cp ∧
      g.natDegree = d * Cp.natDegree ∧ g.Monic := by
  have hfix : (Galois.orbProd (mapRingHom (toHom σ)) d Cp).map (toHom σ) =
      Galois.orbProd (mapRingHom (toHom σ)) d Cp := by
    have h1 : (mapRingHom (toHom σ)) ^ d = 1 := by
      rw [Galois.mapRingHom_pow, toHom_pow_eq_one σ hσ, RingHom.one_def, mapRingHom_id]; rfl
    have := Galois.orbProd_fixed (mapRingHom (toHom σ)) h1 Cp
    rwa [coe_mapRingHom] at this
  have hl : Galois.orbProd (mapRingHom (toHom σ)) d Cp ∈ lifts (algebraMap K L) := by
    rw [lifts_iff_coeff_lifts]
    intro n
    apply mem_range_algebraMap_of_fixed_gen σ hgen
    have := congrArg (fun p : L[X] => p.coeff n) hfix
    simpa [coeff_map] using this
  obtain ⟨g, hg, hdeg, hmon⟩ := lifts_and_natDegree_eq_and_monic hl (orbProd_monic σ d hC)
  exact ⟨g, hg, hdeg.trans (natDegree_orbProd_of_monic σ d hC), hmon⟩

end DegreeKD

section DegreeKDFinite
variable {K L M : Type*} [Field K] [Fintype K] [Field L] [Algebra K L] [Finite L]
  [Field M] [Algebra K M] [Algebra L M] [IsScalarTower K L M] [Finite M]

/-- (Lemma "Norm criterion", sufficiency for `d ∣ deg h`.)  Let `K ⊆ L ⊆ M` be finite
    fields with `d = [L : K]`, `k = [M : L]`.  A monic irreducible `h ∈ K[Y]` of degree
    `kd = [M : K]` is, over `L`, the Frobenius orbit product `Orb_d(C)` of a monic
    `C ∈ L[Y]` of degree `k` (namely `C = minpoly_L(β)` for a root `β ∈ M` of `h`). -/
theorem irreducible_eq_orbProd_of_tower (h : K[X]) (hirr : Irreducible h) (hmon : h.Monic)
    (hdeg : h.natDegree = Module.finrank K M) :
    ∃ Cp : L[X], Cp.Monic ∧ Cp.natDegree = Module.finrank L M ∧
      h.map (algebraMap K L) =
        Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) Cp := by
  obtain ⟨β, hβ⟩ := exists_root_of_irreducible (L := M) h hirr hdeg
  haveI : Module.Finite L M := Module.Finite.of_finite
  set σ : L ≃ₐ[K] L := frob with hσdef
  set d := Module.finrank K L with hd
  set Cp : L[X] := minpoly L β with hCp
  have hCmon : Cp.Monic := minpoly.monic (IsIntegral.of_finite L β)
  obtain ⟨g, hg, hgdeg, hgmon⟩ := orbProd_lifts σ frob_gen frob_pow_finrank hCmon
  -- β is a root of g
  have hgβ : aeval β g = 0 := by
    rw [aeval_def, ← eval_map, IsScalarTower.algebraMap_eq K L M, ← Polynomial.map_map, hg]
    obtain ⟨q, hq⟩ := dvd_orbProd_self σ (Module.finrank_pos (R := K) (M := L)) Cp
    rw [hq, Polynomial.map_mul (algebraMap L M), eval_mul]
    have : (Cp.map (algebraMap L M)).eval β = 0 := by
      rw [eval_map, ← aeval_def, hCp, minpoly.aeval]
    rw [this, zero_mul]
  have hmin : h = minpoly K β := minpoly.eq_of_irreducible_of_monic hirr hβ hmon
  have hdvd : h ∣ g := by rw [hmin]; exact minpoly.dvd K β hgβ
  have hle : g.natDegree ≤ h.natDegree := by
    rw [hgdeg, hdeg, ← Module.finrank_mul_finrank K L M]
    exact Nat.mul_le_mul_left _ (minpoly.natDegree_le β)
  have hgh : g = h := eq_of_monic_of_dvd_of_natDegree_le hmon hgmon hdvd hle
  have hdpos : 0 < d := Module.finrank_pos (R := K) (M := L)
  have hCdeg : Cp.natDegree = Module.finrank L M := by
    have h1 : d * Cp.natDegree = d * Module.finrank L M := by
      rw [← hgdeg, hgh, hdeg, ← Module.finrank_mul_finrank K L M]
    exact Nat.eq_of_mul_eq_mul_left hdpos h1
  exact ⟨Cp, hCmon, hCdeg, by rw [← hgh, hg]⟩

/-- The same for a product of monic irreducibles of degree `[M : K]`: `∏ h_i = Orb_d(C)`
    with `C` monic of degree `|s| · [M : L]`. -/
theorem prod_irreducible_eq_orbProd_of_tower {ι : Type*} (s : Finset ι) (h : ι → K[X])
    (hirr : ∀ i ∈ s, Irreducible (h i)) (hmon : ∀ i ∈ s, (h i).Monic)
    (hdeg : ∀ i ∈ s, (h i).natDegree = Module.finrank K M) :
    ∃ Cp : L[X], Cp.Monic ∧ Cp.natDegree = s.card * Module.finrank L M ∧
      (∏ i ∈ s, h i).map (algebraMap K L) =
        Galois.orbProd (mapRingHom (toHom (frob : L ≃ₐ[K] L))) (Module.finrank K L) Cp := by
  classical
  choose! Cf hCf using fun i (hi : i ∈ s) =>
    irreducible_eq_orbProd_of_tower (L := L) (M := M) (h i) (hirr i hi) (hmon i hi) (hdeg i hi)
  refine ⟨∏ i ∈ s, Cf i, monic_prod_of_monic _ _ (fun i hi => (hCf i hi).1), ?_, ?_⟩
  · rw [natDegree_prod_of_monic _ _ (fun i hi => (hCf i hi).1)]
    rw [Finset.sum_congr rfl (fun i hi => (hCf i hi).2.1), Finset.sum_const, smul_eq_mul]
  · exact norm_form_of_factors _ _ s h _ (fun i hi => (hCf i hi).2.2)

end DegreeKDFinite

section DegreeKDGaloisField
variable (p : ℕ) [Fact p.Prime]

/-- (Lemma "Norm criterion", sufficiency for `d ∣ deg h`, over `F_p`.)  A monic
    irreducible `h ∈ F_p[Y]` of degree `kd` (`k, d ≥ 1`) is `Orb_d(C)` over `F_{p^d}` for a
    monic `C` of degree `k`. -/
theorem irreducible_eq_orbProd_galoisField_of_dvd (d k : ℕ) (hd : d ≠ 0) (hk : k ≠ 0)
    (h : (ZMod p)[X]) (hirr : Irreducible h) (hmon : h.Monic) (hdeg : h.natDegree = k * d) :
    ∃ Cp : (GaloisField p d)[X], Cp.Monic ∧ Cp.natDegree = k ∧
      h.map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
          d Cp := by
  have hkd : k * d ≠ 0 := Nat.mul_ne_zero hk hd
  have hL : Module.finrank (ZMod p) (GaloisField p d) = d := GaloisField.finrank p hd
  have hM : Module.finrank (ZMod p) (GaloisField p (k * d)) = k * d := GaloisField.finrank p hkd
  obtain ⟨f⟩ := FiniteField.nonempty_algHom_of_finrank_dvd (F := ZMod p) (K := GaloisField p d)
    (L := GaloisField p (k * d)) (by rw [hL, hM]; exact Dvd.intro_left k rfl)
  letI : Algebra (GaloisField p d) (GaloisField p (k * d)) := f.toRingHom.toAlgebra
  haveI : IsScalarTower (ZMod p) (GaloisField p d) (GaloisField p (k * d)) :=
    IsScalarTower.of_algebraMap_eq (fun x => (f.commutes x).symm)
  have hLM : Module.finrank (GaloisField p d) (GaloisField p (k * d)) = k := by
    have := Module.finrank_mul_finrank (ZMod p) (GaloisField p d) (GaloisField p (k * d))
    rw [hL, hM] at this
    exact Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero hd) (this.trans (mul_comm k d))
  obtain ⟨Cp, hCm, hCd, hC⟩ := irreducible_eq_orbProd_of_tower (L := GaloisField p d)
    (M := GaloisField p (k * d)) h hirr hmon (by rw [hdeg, hM])
  refine ⟨Cp, hCm, by rw [hCd, hLM], ?_⟩
  rw [hC, hL]

/-- Products of monic irreducibles of degree `kd` over `F_p` (a common `k`) are norm forms
    `Orb_d(C)` with `deg C = k · #factors`. -/
theorem prod_irreducible_eq_orbProd_galoisField_of_dvd (d k : ℕ) (hd : d ≠ 0) (hk : k ≠ 0)
    {ι : Type*} (s : Finset ι) (h : ι → (ZMod p)[X]) (hirr : ∀ i ∈ s, Irreducible (h i))
    (hmon : ∀ i ∈ s, (h i).Monic) (hdeg : ∀ i ∈ s, (h i).natDegree = k * d) :
    ∃ Cp : (GaloisField p d)[X], Cp.Monic ∧ Cp.natDegree = s.card * k ∧
      (∏ i ∈ s, h i).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (mapRingHom (toHom (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)))
          d Cp := by
  classical
  choose! Cf hCf using fun i (hi : i ∈ s) =>
    irreducible_eq_orbProd_galoisField_of_dvd p d k hd hk (h i) (hirr i hi) (hmon i hi) (hdeg i hi)
  refine ⟨∏ i ∈ s, Cf i, monic_prod_of_monic _ _ (fun i hi => (hCf i hi).1), ?_, ?_⟩
  · rw [natDegree_prod_of_monic _ _ (fun i hi => (hCf i hi).1)]
    rw [Finset.sum_congr rfl (fun i hi => (hCf i hi).2.1), Finset.sum_const, smul_eq_mul]
  · exact norm_form_of_factors _ _ s h _ (fun i hi => (hCf i hi).2.2)

end DegreeKDGaloisField

/-! ## 9. Periods of irreducible factors over `L`: the multiplicity criterion (round 5)

Let `π = mapRingHom σ` act on `L[Y]`.  For a monic irreducible `h ∈ K[Y]` and a monic
irreducible factor `h₁ ∈ L[Y]` of `h` over `L`, let `t` be the (minimal) period of `h₁`
under `π`.  Then `h = ∏_{j<t} σʲh₁ = Orb_t(h₁)`, `deg h = t · deg h₁`, `t ∣ d`, and
`Orb_d(h₁) = h^{d/t}`.  Consequently

* (sufficiency)  `d/t ∣ μ  ⟹  h^μ = Orb_d(h₁^{μ t/d})`;
* (necessity)    `F = Orb_d(C)`, `h^μ ∥ F  ⟹  d/t ∣ μ`, hence `d ∣ t μ ∣ m_h μ`.

The necessity is proved by counting the `h₁`-multiplicity of
`Orb_d(C) = Orb^{σ^t}_{d/t}(Orb_t(C))` (each of the `d/t` factors has the same
`h₁`-multiplicity because `σ^t` fixes `h₁`). -/
section PeriodRing
variable {R : Type*} [CommRing R]

/-- `Orb_{t·q}(x) = Orb^{φ^t}_q(Orb_t(x))`: grouping the orbit into `q` blocks of length `t`. -/
theorem orbProd_mul_eq (φ : R →+* R) (t q : ℕ) (x : R) :
    Galois.orbProd φ (t * q) x = Galois.orbProd (φ ^ t) q (Galois.orbProd φ t x) := by
  induction q with
  | zero => simp
  | succ q ih => rw [Nat.mul_succ, Galois.orbProd_add, ih, Galois.orbProd_succ, ← pow_mul]

/-- `Orb_d(x^e) = Orb_d(x)^e`. -/
theorem orbProd_pow (φ : R →+* R) (d : ℕ) (x : R) (e : ℕ) :
    Galois.orbProd φ d (x ^ e) = Galois.orbProd φ d x ^ e := by
  unfold Galois.orbProd
  rw [← Finset.prod_pow]
  exact Finset.prod_congr rfl (fun i _ => map_pow _ _ _)

/-- If `φ^t x = x` then `Orb_t(x)` is `φ`-fixed (cyclic reindexing; generalises
    `Galois.orbProd_fixed`, which assumes `φ^t = 1`). -/
theorem orbProd_fixed_of_period (φ : R →+* R) {t : ℕ} {x : R} (hx : (φ ^ t) x = x) :
    φ (Galois.orbProd φ t x) = Galois.orbProd φ t x := by
  rcases t with _ | m
  · simp
  · have h1 : φ (Galois.orbProd φ (m + 1) x) =
        ∏ i ∈ Finset.range (m + 1), (φ ^ (i + 1)) x := by
      have := Galois.map_orbProd φ 1 (m + 1) x
      rw [pow_one] at this
      rw [this]
      apply Finset.prod_congr rfl
      intro i _; rw [add_comm]
    rw [h1, Finset.prod_range_succ, hx]
    unfold Galois.orbProd
    rw [Finset.prod_range_succ' (fun i => (φ ^ i) x) m, pow_zero, RingHom.one_def,
      RingHom.id_apply]

theorem orbProd_fixed_pow_of_period (φ : R →+* R) {t : ℕ} {x : R} (hx : (φ ^ t) x = x)
    (k : ℕ) : (φ ^ k) (Galois.orbProd φ t x) = Galois.orbProd φ t x := by
  rw [RingHom.coe_pow]; exact Function.iterate_fixed (orbProd_fixed_of_period φ hx) k

/-- `(φ^a) ((φ^b) x) = (φ^(a+b)) x`. -/
theorem pow_apply_pow_apply (φ : R →+* R) (a b : ℕ) (x : R) :
    (φ ^ a) ((φ ^ b) x) = (φ ^ (a + b)) x := by
  rw [pow_add, RingHom.mul_def, RingHom.comp_apply]

end PeriodRing

section PeriodBasic
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The coefficientwise action of `σ` on `L[Y]`. -/
noncomputable abbrev act (σ : L ≃ₐ[K] L) : L[X] →+* L[X] := mapRingHom (toHom σ)

theorem act_pow_apply (σ : L ≃ₐ[K] L) (i : ℕ) (f : L[X]) :
    (act σ ^ i) f = f.map (toHom σ ^ i) := by
  rw [Galois.mapRingHom_pow, coe_mapRingHom]

/-- Base-field polynomials are fixed by `π`. -/
theorem act_map_algebraMap (σ : L ≃ₐ[K] L) (g : K[X]) :
    act σ (g.map (algebraMap K L)) = g.map (algebraMap K L) := by
  simp only [act, coe_mapRingHom, Polynomial.map_map]
  congr 1
  ext x
  simp [toHom_apply]

theorem act_pow_map_algebraMap (σ : L ≃ₐ[K] L) (i : ℕ) (g : K[X]) :
    (act σ ^ i) (g.map (algebraMap K L)) = g.map (algebraMap K L) := by
  rw [RingHom.coe_pow]; exact Function.iterate_fixed (act_map_algebraMap σ g) i

/-- `π^d = 1` when `σ^d = 1`. -/
theorem act_pow_eq_one (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1) : act σ ^ d = 1 := by
  rw [Galois.mapRingHom_pow, toHom_pow_eq_one σ hσ, RingHom.one_def, mapRingHom_id]; rfl

theorem act_pow_monic (σ : L ≃ₐ[K] L) (i : ℕ) {f : L[X]} (hf : f.Monic) :
    ((act σ ^ i) f).Monic := by
  rw [act_pow_apply]; exact hf.map _

theorem act_pow_natDegree (σ : L ≃ₐ[K] L) (i : ℕ) {f : L[X]} (hf : f.Monic) :
    ((act σ ^ i) f).natDegree = f.natDegree := by
  rw [act_pow_apply]; exact hf.natDegree_map _

theorem act_pow_ne_zero (σ : L ≃ₐ[K] L) (i : ℕ) {f : L[X]} (hf : f ≠ 0) :
    (act σ ^ i) f ≠ 0 := by
  rw [act_pow_apply]
  exact (Polynomial.map_ne_zero_iff (toHom σ ^ i).injective).mpr hf

/-- The period `t` of `h₁` under `π` (Mathlib's `Function.minimalPeriod`). -/
noncomputable def period (σ : L ≃ₐ[K] L) (h₁ : L[X]) : ℕ := Function.minimalPeriod (act σ) h₁

theorem act_pow_period (σ : L ≃ₐ[K] L) (h₁ : L[X]) : (act σ ^ period σ h₁) h₁ = h₁ := by
  rw [RingHom.coe_pow]; exact Function.iterate_minimalPeriod

theorem isPeriodicPt_of_pow_eq_one (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1) (h₁ : L[X]) :
    Function.IsPeriodicPt (act σ) d h₁ := by
  show (act σ)^[d] h₁ = h₁
  rw [← RingHom.coe_pow, act_pow_eq_one σ hσ]; rfl

theorem period_pos (σ : L ≃ₐ[K] L) {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1) (h₁ : L[X]) :
    0 < period σ h₁ :=
  (isPeriodicPt_of_pow_eq_one σ hσ h₁).minimalPeriod_pos hd

theorem period_dvd (σ : L ≃ₐ[K] L) {d : ℕ} (hσ : σ ^ d = 1) (h₁ : L[X]) : period σ h₁ ∣ d :=
  (isPeriodicPt_of_pow_eq_one σ hσ h₁).minimalPeriod_dvd

/-- `h₁` is coprime to each conjugate `σʲh₁`, `0 < j < t`. -/
theorem isCoprime_act_pow (σ : L ≃ₐ[K] L) {h₁ : L[X]} (hirr : Irreducible h₁) (hmon : h₁.Monic)
    {j : ℕ} (hj0 : 0 < j) (hjt : j < period σ h₁) : IsCoprime h₁ ((act σ ^ j) h₁) := by
  rw [hirr.coprime_iff_not_dvd]
  intro hdvd
  have heq : (act σ ^ j) h₁ = h₁ :=
    eq_of_monic_of_dvd_of_natDegree_le hmon (act_pow_monic σ j hmon) hdvd
      (by rw [act_pow_natDegree σ j hmon])
  have h := (Function.iterate_eq_iterate_iff_of_lt_minimalPeriod (f := act σ) (x := h₁)
    (m := j) (n := 0) hjt (by unfold period at hjt; omega)).mp
    (by rw [← RingHom.coe_pow, heq]; rfl)
  omega

theorem isCoprime_act_pow_pair (σ : L ≃ₐ[K] L) {h₁ : L[X]} (hirr : Irreducible h₁)
    (hmon : h₁.Monic) {i j : ℕ} (hij : i < j) (hjt : j < period σ h₁) :
    IsCoprime ((act σ ^ i) h₁) ((act σ ^ j) h₁) := by
  have h := (isCoprime_act_pow σ hirr hmon (j := j - i) (by omega) (by omega)).map (act σ ^ i)
  rw [pow_apply_pow_apply, Nat.add_sub_cancel' hij.le] at h
  exact h

/-- The conjugates `σⁱh₁`, `i < t`, are pairwise coprime. -/
theorem pairwise_isCoprime_act_pow (σ : L ≃ₐ[K] L) {h₁ : L[X]} (hirr : Irreducible h₁)
    (hmon : h₁.Monic) :
    ((Finset.range (period σ h₁) : Finset ℕ) : Set ℕ).Pairwise
      (Function.onFun IsCoprime (fun i => (act σ ^ i) h₁)) := by
  intro i hi j hj hij
  simp only [Finset.coe_range, Set.mem_Iio] at hi hj
  simp only [Function.onFun]
  rcases Nat.lt_or_gt_of_ne hij with hlt | hlt
  · exact isCoprime_act_pow_pair σ hirr hmon hlt hj
  · exact (isCoprime_act_pow_pair σ hirr hmon hlt hi).symm

/-! ### Multiplicity bookkeeping (no Galois hypotheses needed) -/

/-- `h₁`-multiplicities are invariant under `π^n` when `π^n h₁ = h₁` (and `π^d = 1`). -/
theorem emultiplicity_act_pow (σ : L ≃ₐ[K] L) {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {h₁ : L[X]} {n : ℕ} (hfix : (act σ ^ n) h₁ = h₁) (D : L[X]) :
    emultiplicity h₁ ((act σ ^ n) D) = emultiplicity h₁ D := by
  have hpow : ∀ k, (act σ ^ n) (h₁ ^ k) = h₁ ^ k := fun k => by rw [map_pow, hfix]
  -- the inverse of `π^n` is `π^{n(d−1)}`
  have hinv : ∀ f : L[X], (act σ ^ (n * (d - 1))) ((act σ ^ n) f) = f := by
    intro f
    rw [pow_apply_pow_apply]
    obtain ⟨d', rfl⟩ : ∃ d', d = d' + 1 := ⟨d - 1, by omega⟩
    have : n * (d' + 1 - 1) + n = (d' + 1) * n := by
      simp only [Nat.add_sub_cancel]; ring
    rw [this, pow_mul, act_pow_eq_one σ hσ, one_pow]; rfl
  have hfix' : ∀ k, (act σ ^ (n * (d - 1))) (h₁ ^ k) = h₁ ^ k := by
    intro k
    rw [map_pow, pow_mul, RingHom.coe_pow]
    congr 1
    exact Function.iterate_fixed hfix _
  apply le_antisymm
  · rw [emultiplicity_le_emultiplicity_iff]
    intro k hk
    have := map_dvd (act σ ^ (n * (d - 1))) hk
    rwa [hfix', hinv] at this
  · rw [emultiplicity_le_emultiplicity_iff]
    intro k hk
    have := map_dvd (act σ ^ n) hk
    rwa [hpow] at this

/-- The `h₁`-multiplicity of `Orb_d(C)` is `(d/t)` times that of `Orb_t(C)`. -/
theorem emultiplicity_orbProd (σ : L ≃ₐ[K] L) {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (Cp : L[X]) :
    emultiplicity h₁ (Galois.orbProd (act σ) d Cp) =
      ((d / period σ h₁ : ℕ) : ℕ∞) *
        emultiplicity h₁ (Galois.orbProd (act σ) (period σ h₁) Cp) := by
  obtain ⟨q, hq⟩ := period_dvd σ hσ h₁
  have htpos := period_pos σ hd hσ h₁
  have hprime : Prime h₁ := hirr₁.prime
  rw [hq, Nat.mul_div_cancel_left _ htpos, orbProd_mul_eq]
  rw [show Galois.orbProd (act σ ^ period σ h₁) q (Galois.orbProd (act σ) (period σ h₁) Cp) =
      ∏ i ∈ Finset.range q, ((act σ ^ period σ h₁) ^ i) (Galois.orbProd (act σ) (period σ h₁) Cp)
    from rfl]
  rw [Finset.emultiplicity_prod hprime]
  have : ∀ i ∈ Finset.range q,
      emultiplicity h₁ (((act σ ^ period σ h₁) ^ i) (Galois.orbProd (act σ) (period σ h₁) Cp)) =
      emultiplicity h₁ (Galois.orbProd (act σ) (period σ h₁) Cp) := by
    intro i _
    rw [← pow_mul]
    apply emultiplicity_act_pow σ hd hσ
    rw [pow_mul, RingHom.coe_pow]
    exact Function.iterate_fixed (act_pow_period σ h₁) i
  rw [Finset.sum_congr rfl this, Finset.sum_const, Finset.card_range, nsmul_eq_mul]

/-- `Orb_d(C) ≠ 0` for `C ≠ 0`. -/
theorem orbProd_ne_zero (σ : L ≃ₐ[K] L) (d : ℕ) {Cp : L[X]} (hC : Cp ≠ 0) :
    Galois.orbProd (act σ) d Cp ≠ 0 := by
  unfold Galois.orbProd
  rw [Finset.prod_ne_zero_iff]
  intro i _
  exact act_pow_ne_zero σ i hC

/-- The `h₁`-multiplicity of `h` over `L` is exactly `1` (`h` separable, `K` perfect). -/
theorem emultiplicity_map_irreducible [PerfectField K] {h : K[X]} (hirr : Irreducible h)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    emultiplicity h₁ (h.map (algebraMap K L)) = 1 := by
  rw [← ENat.coe_one, emultiplicity_eq_coe]
  refine ⟨by simpa using hdvd, ?_⟩
  intro h2
  have hsq : Squarefree (h.map (algebraMap K L)) :=
    (PerfectField.separable_of_irreducible hirr).map.squarefree
  exact hirr₁.not_isUnit (hsq h₁ (by rw [← pow_two]; exact h2))

/-- If `h₁ ∣ h` over `L` and `h ∤ G` in `K[Y]`, then `h₁ ∤ G` over `L`. -/
theorem not_dvd_map_of_not_dvd {h G : K[X]} (hirr : Irreducible h) (hG : ¬ h ∣ G)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    ¬ h₁ ∣ G.map (algebraMap K L) := by
  intro hG₁
  have hcop : IsCoprime h G := hirr.coprime_iff_not_dvd.mpr hG
  have hcop' := hcop.map (mapRingHom (algebraMap K L))
  simp only [coe_mapRingHom] at hcop'
  exact hirr₁.not_isUnit (hcop'.isUnit_of_dvd' hdvd hG₁)

/-- **(Lemma "Norm criterion", necessity, non-squarefree `F`.)**  If `F = Orb_d(C)` over `L`
    (`C ≠ 0`) and `h ∈ K[Y]` is irreducible with exact multiplicity `μ` in `F`
    (`h^μ ∣ F`, `h^{μ+1} ∤ F`), then for every irreducible factor `h₁` of `h` over `L`
    with period `t`:  `d/t ∣ μ`. -/
theorem period_div_dvd_of_orbProd [PerfectField K] (σ : L ≃ₐ[K] L)
    {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {F : K[X]} {Cp : L[X]} (hC : Cp ≠ 0)
    (hF : F.map (algebraMap K L) = Galois.orbProd (act σ) d Cp)
    {h : K[X]} (hirr : Irreducible h) {μ : ℕ} (hμ : h ^ μ ∣ F) (hμ' : ¬ h ^ (μ + 1) ∣ F)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    d / period σ h₁ ∣ μ := by
  have hprime : Prime h₁ := hirr₁.prime
  -- `F = h^μ G` with `h ∤ G`
  obtain ⟨G, hG⟩ := hμ
  have hhG : ¬ h ∣ G := by
    intro hdG
    apply hμ'
    rw [hG, pow_succ]
    exact mul_dvd_mul_left _ hdG
  -- multiplicity of `h₁` in `F` computed from the factorisation: `μ`
  have h1 : emultiplicity h₁ (F.map (algebraMap K L)) = μ := by
    rw [hG, Polynomial.map_mul, Polynomial.map_pow, emultiplicity_mul hprime,
      emultiplicity_pow hprime, emultiplicity_map_irreducible hirr hirr₁ hdvd,
      emultiplicity_eq_zero.mpr (not_dvd_map_of_not_dvd hirr hhG hirr₁ hdvd)]
    simp
  -- multiplicity of `h₁` in `F` computed from the orbit product: `(d/t) · ν`
  have h2 := emultiplicity_orbProd σ hd hσ hirr₁ Cp
  rw [← hF, h1] at h2
  have hfin : FiniteMultiplicity h₁ (Galois.orbProd (act σ) (period σ h₁) Cp) :=
    FiniteMultiplicity.of_not_isUnit hirr₁.not_isUnit (orbProd_ne_zero σ _ hC)
  rw [hfin.emultiplicity_eq_multiplicity] at h2
  have h3 : μ = (d / period σ h₁) * multiplicity h₁ (Galois.orbProd (act σ) (period σ h₁) Cp) := by
    exact_mod_cast h2
  exact ⟨_, h3⟩

end PeriodBasic

section PeriodGalois
variable {K L : Type*} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L] [IsGalois K L]

/-- `Orb_t(C)` of a monic `C` with `π^t C = C` has coefficients in `K` (generalises
    `orbProd_lifts`, which assumes `σ^t = 1`). -/
theorem orbProd_lifts_of_period (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {t : ℕ} {Cp : L[X]} (hC : Cp.Monic) (hper : (act σ ^ t) Cp = Cp) :
    ∃ g : K[X], g.map (algebraMap K L) = Galois.orbProd (act σ) t Cp ∧
      g.natDegree = t * Cp.natDegree ∧ g.Monic := by
  have hfix : (Galois.orbProd (act σ) t Cp).map (toHom σ) = Galois.orbProd (act σ) t Cp := by
    have := orbProd_fixed_of_period (act σ) hper
    rwa [act, coe_mapRingHom] at this
  have hl : Galois.orbProd (act σ) t Cp ∈ lifts (algebraMap K L) := by
    rw [lifts_iff_coeff_lifts]
    intro n
    apply mem_range_algebraMap_of_fixed_gen σ hgen
    have := congrArg (fun p : L[X] => p.coeff n) hfix
    simpa [coeff_map] using this
  obtain ⟨g, hg, hdeg, hmon⟩ := lifts_and_natDegree_eq_and_monic hl (orbProd_monic σ t hC)
  exact ⟨g, hg, hdeg.trans (natDegree_orbProd_of_monic σ t hC), hmon⟩

/-- **Splitting of an irreducible over `L` into its `t` conjugates.**  For `h ∈ K[Y]` monic
    irreducible and `h₁ ∈ L[Y]` a monic irreducible factor of `h` over `L` with period `t`:
    `h = Orb_t(h₁) = ∏_{j<t} σʲh₁` over `L`, and `deg h = t · deg h₁`. -/
theorem map_eq_orbProd_period (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    h.map (algebraMap K L) = Galois.orbProd (act σ) (period σ h₁) h₁ ∧
      h.natDegree = period σ h₁ * h₁.natDegree := by
  have htpos : 0 < period σ h₁ := period_pos σ hd hσ h₁
  -- every conjugate divides `h`
  have hconj : ∀ j ∈ Finset.range (period σ h₁), (act σ ^ j) h₁ ∣ h.map (algebraMap K L) := by
    intro j _
    have := map_dvd (act σ ^ j) hdvd
    rwa [act_pow_map_algebraMap] at this
  have hprod : Galois.orbProd (act σ) (period σ h₁) h₁ ∣ h.map (algebraMap K L) := by
    unfold Galois.orbProd
    exact Finset.prod_dvd_of_coprime (pairwise_isCoprime_act_pow σ hirr₁ hmon₁) hconj
  -- the orbit product lifts to `g ∈ K[Y]` with `g ∣ h`
  obtain ⟨g, hg, hgdeg, hgmon⟩ :=
    orbProd_lifts_of_period σ hgen hmon₁ (act_pow_period σ h₁)
  have hgh : g ∣ h := by
    rw [← map_dvd_map (algebraMap K L) (algebraMap K L).injective hgmon, hg]
    exact hprod
  have hdeg₁ : 0 < h₁.natDegree :=
    natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hirr₁)
  have hgeq : g = h := by
    rcases hirr.dvd_iff.mp hgh with hu | hassoc
    · exfalso
      have h1 := hgmon.eq_one_of_isUnit hu
      rw [h1, natDegree_one] at hgdeg
      have : 0 < period σ h₁ * h₁.natDegree := Nat.mul_pos htpos hdeg₁
      omega
    · exact eq_of_monic_of_associated hgmon hmon hassoc.symm
  subst hgeq
  exact ⟨hg, hgdeg⟩

/-- `Orb_d(h₁) = h^{d/t}` over `L`. -/
theorem orbProd_eq_map_pow (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    Galois.orbProd (act σ) d h₁ = h.map (algebraMap K L) ^ (d / period σ h₁) := by
  obtain ⟨hmap, -⟩ := map_eq_orbProd_period σ hgen hd hσ hirr hmon hirr₁ hmon₁ hdvd
  obtain ⟨q, hq⟩ := period_dvd σ hσ h₁
  have htpos := period_pos σ hd hσ h₁
  rw [hq, Nat.mul_div_cancel_left _ htpos, orbProd_mul_eq, ← hmap,
    orbProd_of_fixed _ _ (act_pow_map_algebraMap σ _ h)]

/-- **(Lemma "Norm criterion", sufficiency, general period.)**  If `d/t ∣ μ` then
    `h^μ = Orb_d(h₁^{μ/(d/t)})` over `L`, with `h₁^{μ/(d/t)}` monic of degree
    `(μ/(d/t)) · deg h₁` (`= μ m_h / d`). -/
theorem pow_eq_orbProd_of_dvd (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) {μ : ℕ} (hμ : d / period σ h₁ ∣ μ) :
    (h₁ ^ (μ / (d / period σ h₁))).Monic ∧
      (h₁ ^ (μ / (d / period σ h₁))).natDegree = (μ / (d / period σ h₁)) * h₁.natDegree ∧
      (h ^ μ).map (algebraMap K L) =
        Galois.orbProd (act σ) d (h₁ ^ (μ / (d / period σ h₁))) := by
  have horb := orbProd_eq_map_pow σ hgen hd hσ hirr hmon hirr₁ hmon₁ hdvd
  obtain ⟨q, hq⟩ := period_dvd σ hσ h₁
  have htpos := period_pos σ hd hσ h₁
  have hqpos : 0 < d / period σ h₁ := Nat.div_pos (Nat.le_of_dvd hd ⟨q, hq⟩) htpos
  obtain ⟨e, he⟩ := hμ
  refine ⟨hmon₁.pow _, hmon₁.natDegree_pow _, ?_⟩
  rw [orbProd_pow, horb, ← pow_mul, Polynomial.map_pow, he, Nat.mul_div_cancel_left _ hqpos]

/-- The paper's form of the necessity: `d ∣ t μ` and hence `d ∣ m_h μ` (`t ∣ m_h`). -/
theorem dvd_natDegree_mul_of_orbProd [PerfectField K] (σ : L ≃ₐ[K] L)
    (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} (hd : 0 < d) (hσ : σ ^ d = 1)
    {F : K[X]} {Cp : L[X]} (hC : Cp ≠ 0)
    (hF : F.map (algebraMap K L) = Galois.orbProd (act σ) d Cp)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {μ : ℕ} (hμ : h ^ μ ∣ F) (hμ' : ¬ h ^ (μ + 1) ∣ F) :
    d ∣ h.natDegree * μ := by
  -- pick a monic irreducible factor `h₁` of `h` over `L`
  have hnu : ¬ IsUnit (h.map (algebraMap K L)) := by
    intro hu
    have h1 := (hmon.map _).eq_one_of_isUnit hu
    have h2 := congrArg natDegree h1
    rw [hmon.natDegree_map, natDegree_one] at h2
    have := natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hirr)
    omega
  obtain ⟨h₁, hmon₁, hirr₁, hdvd⟩ := Polynomial.exists_monic_irreducible_factor _ hnu
  obtain ⟨-, hdeg⟩ := map_eq_orbProd_period σ hgen hd hσ hirr hmon hirr₁ hmon₁ hdvd
  have hq := period_div_dvd_of_orbProd σ hd hσ hC hF hirr hμ hμ' hirr₁ hdvd
  obtain ⟨q, hq'⟩ := period_dvd σ hσ h₁
  have htpos := period_pos σ hd hσ h₁
  rw [hq', Nat.mul_div_cancel_left _ htpos] at hq
  rw [hq', hdeg, mul_assoc]
  exact mul_dvd_mul (dvd_refl _) (hq.trans (dvd_mul_left _ _))

end PeriodGalois

/-! ## 10. Finite fields and `F_p`: the multiplicity criterion (round 5) -/
section PeriodFinite
variable {K L : Type*} [Field K] [Fintype K] [Field L] [Algebra K L] [Finite L]

omit [Fintype K] in
/-- An irreducible of degree dividing `[L : K]` has a root in `L` (generalises
    `exists_root_of_irreducible` from `=` to `∣`). -/
theorem exists_root_of_irreducible_of_dvd (F : K[X]) (hF : Irreducible F)
    (hd : F.natDegree ∣ Module.finrank K L) : ∃ α : L, aeval α F = 0 := by
  haveI : Fact (Irreducible F) := ⟨hF⟩
  have hF0 : F ≠ 0 := hF.ne_zero
  have hfin : Module.finrank K (AdjoinRoot F) = F.natDegree := by
    rw [(AdjoinRoot.powerBasis hF0).finrank, AdjoinRoot.powerBasis_dim]
  obtain ⟨f⟩ := FiniteField.nonempty_algHom_of_finrank_dvd (F := K) (K := AdjoinRoot F) (L := L)
    (by rw [hfin]; exact hd)
  refine ⟨f (AdjoinRoot.root F), ?_⟩
  rw [aeval_algHom_apply, AdjoinRoot.aeval_eq, AdjoinRoot.mk_self, map_zero]

/-- (Sufficiency over finite fields, general period.)  `h ∈ K[Y]` monic irreducible, `h₁`
    a monic irreducible factor of `h` over `L` with Frobenius period `t`, `d = [L : K]`,
    `d/t ∣ μ`  ⟹  `h^μ = Orb_d(h₁^{μ/(d/t)})`. -/
theorem pow_eq_orbProd_of_dvd_finite {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) {μ : ℕ}
    (hμ : Module.finrank K L / period (frob : L ≃ₐ[K] L) h₁ ∣ μ) :
    (h ^ μ).map (algebraMap K L) =
      Galois.orbProd (act (frob : L ≃ₐ[K] L)) (Module.finrank K L)
        (h₁ ^ (μ / (Module.finrank K L / period (frob : L ≃ₐ[K] L) h₁))) :=
  (pow_eq_orbProd_of_dvd (frob : L ≃ₐ[K] L) frob_gen Module.finrank_pos frob_pow_finrank
    hirr hmon hirr₁ hmon₁ hdvd hμ).2.2

/-- The degree identity `deg h = t · deg h₁` over finite fields. -/
theorem natDegree_eq_period_mul_finite {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    h.natDegree = period (frob : L ≃ₐ[K] L) h₁ * h₁.natDegree :=
  (map_eq_orbProd_period (frob : L ≃ₐ[K] L) frob_gen Module.finrank_pos frob_pow_finrank
    hirr hmon hirr₁ hmon₁ hdvd).2

/-- (Sufficiency, the case `m_h ∣ d`: `h` splits into `m_h` linear conjugates `Y − σⁱβ`.)
    If `deg h ∣ d = [L : K]` and `d / deg h ∣ μ`, then `h^μ = Orb_d((Y − β)^{μ/(d/deg h)})`
    for a root `β ∈ L` of `h`. -/
theorem pow_eq_orbProd_of_natDegree_dvd {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    (hm : h.natDegree ∣ Module.finrank K L) {μ : ℕ}
    (hμ : Module.finrank K L / h.natDegree ∣ μ) :
    ∃ β : L, aeval β h = 0 ∧
      (h ^ μ).map (algebraMap K L) =
        Galois.orbProd (act (frob : L ≃ₐ[K] L)) (Module.finrank K L)
          ((X - C β) ^ (μ / (Module.finrank K L / h.natDegree))) := by
  obtain ⟨β, hβ⟩ := exists_root_of_irreducible_of_dvd (L := L) h hirr hm
  have hdvd : X - C β ∣ h.map (algebraMap K L) := by
    rw [dvd_iff_isRoot, IsRoot.def, eval_map, ← aeval_def]; exact hβ
  have hper : period (frob : L ≃ₐ[K] L) (X - C β) = h.natDegree := by
    have := natDegree_eq_period_mul_finite (L := L) hirr hmon (irreducible_X_sub_C β)
      (monic_X_sub_C β) hdvd
    rw [natDegree_X_sub_C, mul_one] at this
    exact this.symm
  refine ⟨β, hβ, ?_⟩
  have := pow_eq_orbProd_of_dvd_finite (L := L) hirr hmon (irreducible_X_sub_C β)
    (monic_X_sub_C β) hdvd (μ := μ) (by rw [hper]; exact hμ)
  rw [hper] at this
  exact this

/-- (Necessity over finite fields.)  `F = Orb_d(C)` over `L`, `C ≠ 0`, `h` monic irreducible
    with exact multiplicity `μ` in `F`  ⟹  `d ∣ m_h μ` (`d = [L : K]`). -/
theorem dvd_natDegree_mul_of_orbProd_finite {F : K[X]} {Cp : L[X]} (hC : Cp ≠ 0)
    (hF : F.map (algebraMap K L) =
      Galois.orbProd (act (frob : L ≃ₐ[K] L)) (Module.finrank K L) Cp)
    {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {μ : ℕ} (hμ : h ^ μ ∣ F) (hμ' : ¬ h ^ (μ + 1) ∣ F) :
    Module.finrank K L ∣ h.natDegree * μ :=
  dvd_natDegree_mul_of_orbProd (frob : L ≃ₐ[K] L) frob_gen Module.finrank_pos frob_pow_finrank
    hC hF hirr hmon hμ hμ'

/-- The period form of the necessity over finite fields: for every irreducible factor
    `h₁` of `h` over `L`, `d / t(h₁) ∣ μ`. -/
theorem period_div_dvd_of_orbProd_finite {F : K[X]} {Cp : L[X]} (hC : Cp ≠ 0)
    (hF : F.map (algebraMap K L) =
      Galois.orbProd (act (frob : L ≃ₐ[K] L)) (Module.finrank K L) Cp)
    {h : K[X]} (hirr : Irreducible h) {μ : ℕ} (hμ : h ^ μ ∣ F) (hμ' : ¬ h ^ (μ + 1) ∣ F)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hdvd : h₁ ∣ h.map (algebraMap K L)) :
    Module.finrank K L / period (frob : L ≃ₐ[K] L) h₁ ∣ μ :=
  period_div_dvd_of_orbProd (frob : L ≃ₐ[K] L) Module.finrank_pos frob_pow_finrank hC hF hirr
    hμ hμ' hirr₁ hdvd

end PeriodFinite

section PeriodGaloisField
variable (p : ℕ) [Fact p.Prime] (d : ℕ)

/-- (Lemma "Norm criterion" over `F_p`, sufficiency, general period.)  For `h ∈ F_p[Y]` monic
    irreducible, `h₁` a monic irreducible factor of `h` over `F_{p^d}` with Frobenius period
    `t` (so `deg h = t · deg h₁`): if `d/t ∣ μ` then `h^μ = Orb_d(h₁^{μ t/d})`. -/
theorem pow_eq_orbProd_galoisField (hd : d ≠ 0) {h : (ZMod p)[X]} (hirr : Irreducible h)
    (hmon : h.Monic) {h₁ : (GaloisField p d)[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap (ZMod p) (GaloisField p d))) {μ : ℕ}
    (hμ : d / period (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d) h₁ ∣ μ) :
    h.natDegree = period (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d) h₁ * h₁.natDegree ∧
      (h ^ μ).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d
          (h₁ ^ (μ / (d / period (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d) h₁))) := by
  have hfr := finrank_galoisField p d hd
  refine ⟨natDegree_eq_period_mul_finite hirr hmon hirr₁ hmon₁ hdvd, ?_⟩
  have := pow_eq_orbProd_of_dvd_finite (L := GaloisField p d) hirr hmon hirr₁ hmon₁ hdvd
    (μ := μ) (by rw [hfr]; exact hμ)
  rw [hfr] at this
  exact this

/-- (Over `F_p`, the case `m_h ∣ d`.)  `deg h = m ∣ d`, `d/m ∣ μ`  ⟹
    `h^μ = Orb_d((Y − β)^{μ m/d})` for a root `β ∈ F_{p^d}`. -/
theorem pow_eq_orbProd_galoisField_of_natDegree_dvd (hd : d ≠ 0) {h : (ZMod p)[X]}
    (hirr : Irreducible h) (hmon : h.Monic) (hm : h.natDegree ∣ d) {μ : ℕ}
    (hμ : d / h.natDegree ∣ μ) :
    ∃ β : GaloisField p d, aeval β h = 0 ∧
      (h ^ μ).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d
          ((X - C β) ^ (μ / (d / h.natDegree))) := by
  have hfr := finrank_galoisField p d hd
  obtain ⟨β, hβ, h⟩ := pow_eq_orbProd_of_natDegree_dvd (L := GaloisField p d) hirr hmon
    (by rw [hfr]; exact hm) (μ := μ) (by rw [hfr]; exact hμ)
  rw [hfr] at h
  exact ⟨β, hβ, h⟩

/-- (Lemma "Norm criterion" over `F_p`, necessity, non-squarefree `F`.)  If
    `F = Orb_d(C)` over `F_{p^d}` with `C ≠ 0`, then every monic irreducible `h` with exact
    multiplicity `μ` in `F` satisfies `d ∣ m_h μ`. -/
theorem dvd_natDegree_mul_galoisField (hd : d ≠ 0) {F : (ZMod p)[X]}
    {Cp : (GaloisField p d)[X]} (hC : Cp ≠ 0)
    (hF : F.map (algebraMap (ZMod p) (GaloisField p d)) =
      Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d Cp)
    {h : (ZMod p)[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {μ : ℕ} (hμ : h ^ μ ∣ F) (hμ' : ¬ h ^ (μ + 1) ∣ F) :
    d ∣ h.natDegree * μ := by
  have hfr := finrank_galoisField p d hd
  rw [← hfr]
  apply dvd_natDegree_mul_of_orbProd_finite hC _ hirr hmon hμ hμ'
  rw [hF, hfr]

end PeriodGaloisField

/-! ## 11. The period is `gcd(m_h, d)` (round 5)

Over finite fields the minimal polynomial of `β` over `E` is `∏_{i<n} (Y − β^{|E|^i})` with
`n = deg minpoly_E β` and pairwise distinct roots.  Applied to `E = K` and `E = L` in a tower
`K ⊆ L ⊆ M ∋ β` (a root of `h₁`), the `L`-conjugates `β^{q^{dj}}` of `β` are among the
`K`-conjugates `β^{q^{i}}` with `i ≡ dj (mod m)`, i.e. `i` a multiple of `g = gcd(m,d)`; so
`deg h₁ ≤ m/g`.  With `deg h = t · deg h₁` and `t ∣ g` this forces `t = g`.  Hence the
sufficiency hypothesis `d/t ∣ μ` is exactly the paper's `d ∣ m_h μ`. -/
section ConjFixed
variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- `conjProd_map_eq` with the weaker hypothesis `σ^d α = α`. -/
theorem conjProd_map_eq_of_fixed (σ : L ≃ₐ[K] L) {d : ℕ} {α : L} (hα : (σ ^ d) α = α) :
    (conjProd σ d α).map (toHom σ) = conjProd σ d α := by
  unfold conjProd
  rw [Polynomial.map_prod]
  have h1 : ∀ i, (X - C ((σ ^ i) α)).map (toHom σ) = X - C ((σ ^ (i + 1)) α) := by
    intro i
    rw [Polynomial.map_sub, map_X, map_C, toHom_apply, pow_succ', AlgEquiv.mul_apply]
  simp_rw [h1]
  have h2 : ((σ ^ d) α) = (σ ^ 0) α := by rw [hα, pow_zero]; rfl
  have hA := Finset.prod_range_succ (fun i => (X - C ((σ ^ i) α) : L[X])) d
  have hB := Finset.prod_range_succ' (fun i => (X - C ((σ ^ i) α) : L[X])) d
  rw [hA, h2] at hB
  exact mul_right_cancel₀ (X_sub_C_ne_zero _) hB.symm

variable [FiniteDimensional K L] [IsGalois K L]

theorem conjProd_lifts_of_fixed (σ : L ≃ₐ[K] L) (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ)
    {d : ℕ} {α : L} (hα : (σ ^ d) α = α) :
    ∃ g : K[X], g.map (algebraMap K L) = conjProd σ d α ∧ g.natDegree = d ∧ g.Monic := by
  have hl : conjProd σ d α ∈ lifts (algebraMap K L) := by
    rw [lifts_iff_coeff_lifts]
    intro n
    apply mem_range_algebraMap_of_fixed_gen σ hgen
    have := congrArg (fun p : L[X] => p.coeff n) (conjProd_map_eq_of_fixed σ hα)
    simpa [coeff_map] using this
  obtain ⟨g, hg, hdeg, hmon⟩ := lifts_and_natDegree_eq_and_monic hl (conjProd_monic σ d α)
  exact ⟨g, hg, hdeg.trans (conjProd_natDegree σ d α), hmon⟩

/-- `minpoly_map_eq_conjProd` with `σ^d α = α` in place of `σ^d = 1`. -/
theorem minpoly_map_eq_conjProd_of_fixed (σ : L ≃ₐ[K] L)
    (hgen : ∀ τ : L ≃ₐ[K] L, ∃ i : ℕ, σ ^ i = τ) {d : ℕ} (hd : 0 < d)
    (α : L) (hdeg : (minpoly K α).natDegree = d) (hα : (σ ^ d) α = α) :
    (minpoly K α).map (algebraMap K L) = conjProd σ d α := by
  obtain ⟨g, hg, hgdeg, hgmon⟩ := conjProd_lifts_of_fixed σ hgen hα
  have hroot : aeval α g = 0 := by
    rw [aeval_def, ← eval_map, hg]; exact eval_conjProd σ hd α
  have hdvd : minpoly K α ∣ g := minpoly.dvd K α hroot
  have hmin : (minpoly K α).Monic := minpoly.monic (IsIntegral.of_finite K α)
  have heq : minpoly K α = g := by
    apply eq_of_monic_of_associated hmin hgmon
    obtain ⟨q, hq⟩ := hdvd
    have hq0 : q ≠ 0 := by rintro rfl; rw [mul_zero] at hq; exact hgmon.ne_zero hq
    have hdq : q.natDegree = 0 := by
      have := congrArg natDegree hq
      rw [natDegree_mul hmin.ne_zero hq0, hdeg, hgdeg] at this
      omega
    rw [hq]
    apply associated_mul_unit_right
    rw [isUnit_iff_degree_eq_zero, degree_eq_natDegree hq0, hdq]
    rfl
  rw [heq, hg]

end ConjFixed

section MinpolyFinite
variable {K L : Type*} [Field K] [Fintype K] [Field L] [Algebra K L] [Finite L]

/-- `σⁱ x = x^{|K|^i}` for the Frobenius `σ`. -/
theorem frob_pow_apply (i : ℕ) (x : L) :
    ((frob : L ≃ₐ[K] L) ^ i) x = x ^ (Fintype.card K ^ i) := by
  induction i with
  | zero => simp
  | succ i ih => rw [pow_succ', AlgEquiv.mul_apply, ih, frob_apply, ← pow_mul, ← pow_succ]

/-- `β^{|K|^n} = β` for `n = deg minpoly_K β` (`K(β)` has `|K|^n` elements). -/
theorem pow_card_pow_natDegree_minpoly (β : L) :
    β ^ (Fintype.card K ^ (minpoly K β).natDegree) = β := by
  have hint : IsIntegral K β := IsIntegral.of_finite K β
  haveI : Fintype (IntermediateField.adjoin K {β}) := Fintype.ofFinite _
  have hcard : Fintype.card (IntermediateField.adjoin K {β}) =
      Fintype.card K ^ (minpoly K β).natDegree := by
    rw [Module.card_eq_pow_finrank (K := K) (V := IntermediateField.adjoin K {β}),
      IntermediateField.adjoin.finrank hint]
  have h := FiniteField.pow_card
    (⟨β, IntermediateField.mem_adjoin_simple_self K β⟩ : IntermediateField.adjoin K {β})
  rw [hcard] at h
  have := congrArg Subtype.val h
  simpa using this

theorem frob_pow_natDegree_minpoly (β : L) :
    ((frob : L ≃ₐ[K] L) ^ (minpoly K β).natDegree) β = β := by
  rw [frob_pow_apply]; exact pow_card_pow_natDegree_minpoly β

/-- **Roots of a minimal polynomial over a finite field are the Frobenius conjugates**:
    `minpoly_K β = ∏_{i<n} (Y − β^{|K|^i})` over `L`, `n = deg minpoly_K β`. -/
theorem minpoly_map_eq_conjProd_finite (β : L) :
    (minpoly K β).map (algebraMap K L) =
      conjProd (frob : L ≃ₐ[K] L) (minpoly K β).natDegree β :=
  minpoly_map_eq_conjProd_of_fixed (frob : L ≃ₐ[K] L) frob_gen
    (minpoly.natDegree_pos (IsIntegral.of_finite K β)) β rfl (frob_pow_natDegree_minpoly β)

/-- The `n` conjugates `σⁱβ`, `i < n`, are pairwise distinct (`minpoly` is separable). -/
theorem frob_pow_apply_injOn (β : L) :
    Set.InjOn (fun i : ℕ => ((frob : L ≃ₐ[K] L) ^ i) β)
      (Set.Iio (minpoly K β).natDegree) := by
  have hint : IsIntegral K β := IsIntegral.of_finite K β
  have hsep : ((minpoly K β).map (algebraMap K L)).Separable :=
    (PerfectField.separable_of_irreducible (minpoly.irreducible hint)).map
  have hnd := nodup_roots hsep
  have hcomp : (fun i : ℕ => (X - C (((frob : L ≃ₐ[K] L) ^ i) β) : L[X])) =
      (fun a : L => X - C a) ∘ (fun i : ℕ => ((frob : L ≃ₐ[K] L) ^ i) β) := rfl
  rw [minpoly_map_eq_conjProd_finite, conjProd, Finset.prod_eq_multiset_prod, hcomp,
    ← Multiset.map_map, roots_multiset_prod_X_sub_C] at hnd
  intro i hi j hj hij
  exact Multiset.inj_on_of_nodup_map hnd i (by simpa using hi) j (by simpa using hj) hij

/-- `σⁱ β = σ^{i mod n} β` for `n = deg minpoly_K β`. -/
theorem frob_pow_apply_mod (β : L) (i : ℕ) :
    ((frob : L ≃ₐ[K] L) ^ i) β =
      ((frob : L ≃ₐ[K] L) ^ (i % (minpoly K β).natDegree)) β := by
  have hfix : ∀ k, ((frob : L ≃ₐ[K] L) ^ ((minpoly K β).natDegree * k)) β = β := by
    intro k
    rw [pow_mul, AlgEquiv.coe_pow]
    exact Function.iterate_fixed (frob_pow_natDegree_minpoly β) k
  conv_lhs => rw [← Nat.mod_add_div i (minpoly K β).natDegree, pow_add, AlgEquiv.mul_apply, hfix]

end MinpolyFinite

section PeriodGcd
variable {K L M : Type*} [Field K] [Fintype K] [Field L] [Fintype L] [Algebra K L]
  [Field M] [Finite M] [Algebra K M] [Algebra L M] [IsScalarTower K L M]

/-- **`t = gcd(m_h, d)`.**  In a tower of finite fields `K ⊆ L ⊆ M` with `d = [L : K]`, let
    `h ∈ K[Y]` be monic irreducible of degree `m`, `h₁ ∈ L[Y]` a monic irreducible factor of
    `h` over `L`, and `β ∈ M` a root of `h₁`.  Then the Frobenius period of `h₁` is
    `gcd(m, d)`, i.e. `h` splits over `L` into `gcd(m, d)` conjugates of degree `m/gcd(m,d)`. -/
theorem period_eq_gcd_of_tower {h : K[X]} (hirr : Irreducible h) (hmon : h.Monic)
    {h₁ : L[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap K L)) {β : M} (hβ : aeval β h₁ = 0) :
    period (frob : L ≃ₐ[K] L) h₁ = Nat.gcd h.natDegree (Module.finrank K L) := by
  -- notation
  have hmn := natDegree_eq_period_mul_finite (L := L) hirr hmon hirr₁ hmon₁ hdvd
  have htd := period_dvd (frob : L ≃ₐ[K] L) frob_pow_finrank h₁
  have htpos := period_pos (frob : L ≃ₐ[K] L) Module.finrank_pos frob_pow_finrank h₁
  have hn₁ : 0 < h₁.natDegree := natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hirr₁)
  have htg : period (frob : L ≃ₐ[K] L) h₁ ∣ Nat.gcd h.natDegree (Module.finrank K L) :=
    Nat.dvd_gcd ⟨_, hmn⟩ htd
  -- `β` is a root of `h`, so `minpoly K β = h`, `minpoly L β = h₁`
  have hβK : aeval β h = 0 := by
    obtain ⟨c, hc⟩ := hdvd
    rw [aeval_def, ← eval_map, IsScalarTower.algebraMap_eq K L M, ← Polynomial.map_map, hc,
      Polynomial.map_mul, eval_mul]
    have : (h₁.map (algebraMap L M)).eval β = 0 := by rw [eval_map, ← aeval_def]; exact hβ
    rw [this, zero_mul]
  have hminK : minpoly K β = h := (minpoly.eq_of_irreducible_of_monic hirr hβK hmon).symm
  have hminL : minpoly L β = h₁ := (minpoly.eq_of_irreducible_of_monic hirr₁ hβ hmon₁).symm
  -- Frobenius over `K` and over `L` on `M`
  have hcardL : Fintype.card L = Fintype.card K ^ Module.finrank K L :=
    Module.card_eq_pow_finrank
  have hψφ : ∀ j, ((frob : M ≃ₐ[L] M) ^ j) β =
      ((frob : M ≃ₐ[K] M) ^ (Module.finrank K L * j)) β := by
    intro j
    rw [frob_pow_apply, frob_pow_apply, hcardL, ← pow_mul]
  -- the `L`-conjugates are `K`-conjugates with exponent `≡ d j (mod m)`, a multiple of `g`
  set m := h.natDegree with hm
  set d := Module.finrank K L with hd
  set g := Nat.gcd m d with hg
  set n := h₁.natDegree with hn
  have hmpos : 0 < m := by rw [hmn]; exact Nat.mul_pos htpos hn₁
  have hgm : g ∣ m := Nat.gcd_dvd_left _ _
  have hgd : g ∣ d := Nat.gcd_dvd_right _ _
  have hgpos : 0 < g := Nat.gcd_pos_of_pos_left _ hmpos
  let f : ℕ → ℕ := fun j => (d * j) % m
  have hf_inj : Set.InjOn f (Set.Iio n) := by
    intro i hi j hj hij
    have h1 := frob_pow_apply_injOn (K := L) β
    rw [hminL] at h1
    apply h1 hi hj
    simp only
    rw [hψφ, hψφ, frob_pow_apply_mod (K := K) β, hminK,
      frob_pow_apply_mod (K := K) β (d * j), hminK]
    exact congrArg (fun k : ℕ => ((frob : M ≃ₐ[K] M) ^ k) β) hij
  have hf_mem : ∀ j, f j ∈ (Finset.range (m / g)).image (fun k => k * g) := by
    intro j
    rw [Finset.mem_image]
    have hgf : g ∣ f j := by
      show g ∣ (d * j) % m
      rw [Nat.dvd_mod_iff hgm]
      exact hgd.mul_right _
    obtain ⟨k, hk⟩ := hgf
    refine ⟨k, Finset.mem_range.mpr ?_, by rw [hk, mul_comm]⟩
    have hlt : f j < m := Nat.mod_lt _ hmpos
    rw [hk] at hlt
    obtain ⟨m', hm'⟩ := hgm
    rw [hm', Nat.mul_div_cancel_left _ hgpos]
    rw [hm'] at hlt
    exact Nat.lt_of_mul_lt_mul_left hlt
  -- counting: `n ≤ m / g`
  have hcount : n ≤ m / g := by
    classical
    have h1 : ((Finset.range n).image f).card = n := by
      rw [Finset.card_image_of_injOn (by simpa using hf_inj), Finset.card_range]
    have h2 : (Finset.range n).image f ⊆ (Finset.range (m / g)).image (fun k => k * g) := by
      intro x hx
      rw [Finset.mem_image] at hx
      obtain ⟨j, _, rfl⟩ := hx
      exact hf_mem j
    have h3 := Finset.card_le_card h2
    rw [h1] at h3
    exact h3.trans (Finset.card_image_le.trans (by rw [Finset.card_range]))
  -- conclude `g ≤ t`, hence `t = g`
  have hng : n * g ≤ m := (Nat.le_div_iff_mul_le hgpos).mp hcount
  rw [hmn] at hng
  have hgt : g ≤ period (frob : L ≃ₐ[K] L) h₁ := by
    rw [mul_comm] at hng
    exact Nat.le_of_mul_le_mul_right hng hn₁
  exact le_antisymm (Nat.le_of_dvd hgpos htg) hgt

end PeriodGcd

section PeriodGcdGaloisField
variable (p : ℕ) [Fact p.Prime] (d : ℕ)

/-- Over `F_p`: the Frobenius period of any monic irreducible factor `h₁` of `h` over
    `F_{p^d}` is `gcd(deg h, d)`; the tower is realised in `F_{p^{d · deg h₁}}`. -/
theorem period_eq_gcd_galoisField (hd : d ≠ 0) {h : (ZMod p)[X]} (hirr : Irreducible h)
    (hmon : h.Monic) {h₁ : (GaloisField p d)[X]} (hirr₁ : Irreducible h₁) (hmon₁ : h₁.Monic)
    (hdvd : h₁ ∣ h.map (algebraMap (ZMod p) (GaloisField p d))) :
    period (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d) h₁ = Nat.gcd h.natDegree d := by
  have hfr := finrank_galoisField p d hd
  have hn₁ : h₁.natDegree ≠ 0 :=
    (natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hirr₁)).ne'
  have hdn : d * h₁.natDegree ≠ 0 := Nat.mul_ne_zero hd hn₁
  have hL : Module.finrank (ZMod p) (GaloisField p d) = d := hfr
  have hM : Module.finrank (ZMod p) (GaloisField p (d * h₁.natDegree)) = d * h₁.natDegree :=
    GaloisField.finrank p hdn
  obtain ⟨f⟩ := FiniteField.nonempty_algHom_of_finrank_dvd (F := ZMod p) (K := GaloisField p d)
    (L := GaloisField p (d * h₁.natDegree)) (by rw [hL, hM]; exact Dvd.intro _ rfl)
  letI : Algebra (GaloisField p d) (GaloisField p (d * h₁.natDegree)) := f.toRingHom.toAlgebra
  haveI : IsScalarTower (ZMod p) (GaloisField p d) (GaloisField p (d * h₁.natDegree)) :=
    IsScalarTower.of_algebraMap_eq (fun x => (f.commutes x).symm)
  have hLM : Module.finrank (GaloisField p d) (GaloisField p (d * h₁.natDegree)) = h₁.natDegree := by
    have := Module.finrank_mul_finrank (ZMod p) (GaloisField p d) (GaloisField p (d * h₁.natDegree))
    rw [hL, hM] at this
    exact Nat.eq_of_mul_eq_mul_left (Nat.pos_of_ne_zero hd) this
  obtain ⟨β, hβ⟩ := exists_root_of_irreducible_of_dvd (L := GaloisField p (d * h₁.natDegree)) h₁
    hirr₁ (by rw [hLM])
  haveI : Fintype (GaloisField p d) := Fintype.ofFinite _
  have := period_eq_gcd_of_tower (M := GaloisField p (d * h₁.natDegree)) hirr hmon hirr₁ hmon₁
    hdvd hβ
  rw [hL] at this
  exact this

/-- **(Lemma "Norm criterion" over `F_p`, sufficiency, the paper's form.)**  `h ∈ F_p[Y]`
    monic irreducible of degree `m`, `d ∣ m μ`  ⟹  `h^μ = Orb_d(C)` over `F_{p^d}` for a
    monic `C` of degree `m μ / d` (namely `C = h₁^{μ gcd(m,d)/d}` for a monic irreducible
    factor `h₁` of `h` over `F_{p^d}`). -/
theorem pow_eq_orbProd_galoisField_of_dvd_mul (hd : d ≠ 0) {h : (ZMod p)[X]}
    (hirr : Irreducible h) (hmon : h.Monic) {μ : ℕ} (hμ : d ∣ h.natDegree * μ) :
    ∃ Cp : (GaloisField p d)[X], Cp.Monic ∧ Cp.natDegree = h.natDegree * μ / d ∧
      (h ^ μ).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d Cp := by
  have hfr := finrank_galoisField p d hd
  -- a monic irreducible factor of `h` over `F_{p^d}`
  have hnu : ¬ IsUnit (h.map (algebraMap (ZMod p) (GaloisField p d))) := by
    intro hu
    have h1 := (hmon.map _).eq_one_of_isUnit hu
    have h2 := congrArg natDegree h1
    rw [hmon.natDegree_map, natDegree_one] at h2
    have := natDegree_pos_iff_degree_pos.mpr (degree_pos_of_irreducible hirr)
    omega
  obtain ⟨h₁, hmon₁, hirr₁, hdvd⟩ := Polynomial.exists_monic_irreducible_factor _ hnu
  have hper := period_eq_gcd_galoisField p d hd hirr hmon hirr₁ hmon₁ hdvd
  obtain ⟨g, hg⟩ : ∃ g, Nat.gcd h.natDegree d = g := ⟨_, rfl⟩
  rw [hg] at hper
  have hmn : h.natDegree = g * h₁.natDegree := by
    have := natDegree_eq_period_mul_finite (L := GaloisField p d) hirr hmon hirr₁ hmon₁ hdvd
    rwa [hper] at this
  have hgd : g ∣ d := hg ▸ Nat.gcd_dvd_right _ _
  have hgm : g ∣ h.natDegree := hg ▸ Nat.gcd_dvd_left _ _
  have hgpos : 0 < g := hg ▸ Nat.gcd_pos_of_pos_right _ (Nat.pos_of_ne_zero hd)
  have hdpos : 0 < d := Nat.pos_of_ne_zero hd
  have hkpos : 0 < d / g := Nat.div_pos (Nat.le_of_dvd hdpos hgd) hgpos
  -- `d ∣ m μ` ⟺ `d/g ∣ μ`
  have hdg : d / g ∣ μ := by
    have hcop : Nat.Coprime (d / g) (h.natDegree / g) := by
      have := (Nat.coprime_div_gcd_div_gcd (m := h.natDegree) (n := d) (hg ▸ hgpos)).symm
      rwa [hg] at this
    have h1 : g * (d / g) ∣ g * (h.natDegree / g * μ) := by
      rw [Nat.mul_div_cancel' hgd, ← mul_assoc, Nat.mul_div_cancel' hgm]; exact hμ
    exact hcop.dvd_of_dvd_mul_left (Nat.dvd_of_mul_dvd_mul_left hgpos h1)
  obtain ⟨-, hpow⟩ := pow_eq_orbProd_galoisField p d hd hirr hmon hirr₁ hmon₁ hdvd
    (μ := μ) (by rw [hper]; exact hdg)
  refine ⟨_, hmon₁.pow _, ?_, by rw [hper] at hpow; exact hpow⟩
  rw [hmon₁.natDegree_pow, hmn]
  -- `(μ / (d/g)) · deg h₁ = g · deg h₁ · μ / d`
  obtain ⟨e, he⟩ := hdg
  rw [he, Nat.mul_div_cancel_left _ hkpos]
  have : g * h₁.natDegree * (d / g * e) = d * (e * h₁.natDegree) := by
    rw [show g * h₁.natDegree * (d / g * e) = (g * (d / g)) * (e * h₁.natDegree) by ring,
      Nat.mul_div_cancel' hgd]
  rw [this, Nat.mul_div_cancel_left _ hdpos]

/-- **(Lemma "Norm criterion" over `F_p`, both directions, per irreducible factor.)**
    For `h` monic irreducible of degree `m` and `μ ≥ 0`:
    `h^μ` is a norm form `Orb_d(C)` over `F_{p^d}`  ⟺  `d ∣ m μ`. -/
theorem pow_eq_orbProd_galoisField_iff (hd : d ≠ 0) {h : (ZMod p)[X]}
    (hirr : Irreducible h) (hmon : h.Monic) (μ : ℕ) :
    (∃ Cp : (GaloisField p d)[X], Cp ≠ 0 ∧
        (h ^ μ).map (algebraMap (ZMod p) (GaloisField p d)) =
          Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d Cp) ↔
      d ∣ h.natDegree * μ := by
  constructor
  · rintro ⟨Cp, hC, hF⟩
    apply dvd_natDegree_mul_galoisField p d hd hC hF hirr hmon (dvd_refl _)
    rw [pow_succ]
    intro hcontra
    have h0 : h ^ μ * h ∣ h ^ μ * 1 := by rw [mul_one]; exact hcontra
    have h1 := (mul_dvd_mul_iff_left (pow_ne_zero μ hirr.ne_zero)).mp h0
    exact hirr.not_isUnit (isUnit_of_dvd_one h1)
  · intro hμ
    obtain ⟨Cp, hCm, -, hF⟩ := pow_eq_orbProd_galoisField_of_dvd_mul p d hd hirr hmon hμ
    exact ⟨Cp, hCm.ne_zero, hF⟩

end PeriodGcdGaloisField

/-! ## 12. The full norm criterion over `F_p` for a factored `F` (round 5) -/
section FullCriterion
variable (p : ℕ) [Fact p.Prime] (d : ℕ)

/-- In `F = ∏_{i∈s} hᵢ^{μᵢ}` with pairwise distinct monic irreducibles `hᵢ`, the exact
    multiplicity of `hᵢ` is `μᵢ`. -/
theorem exact_multiplicity_of_prod {K : Type*} [Field K] {ι : Type*} (s : Finset ι)
    (h : ι → K[X]) (μ : ι → ℕ) (hirr : ∀ i ∈ s, Irreducible (h i))
    (hmon : ∀ i ∈ s, (h i).Monic) (hdist : ∀ i ∈ s, ∀ j ∈ s, h i = h j → i = j)
    {i : ι} (hi : i ∈ s) :
    h i ^ μ i ∣ ∏ j ∈ s, h j ^ μ j ∧ ¬ h i ^ (μ i + 1) ∣ ∏ j ∈ s, h j ^ μ j := by
  classical
  refine ⟨Finset.dvd_prod_of_mem _ hi, ?_⟩
  intro hcontra
  rw [← Finset.mul_prod_erase _ _ hi, pow_succ] at hcontra
  have hne : h i ^ μ i ≠ 0 := pow_ne_zero _ (hirr i hi).ne_zero
  have h1 : h i ∣ ∏ j ∈ s.erase i, h j ^ μ j := (mul_dvd_mul_iff_left hne).mp hcontra
  have hprime : Prime (h i) := (hirr i hi).prime
  rw [hprime.dvd_finsetProd_iff] at h1
  obtain ⟨j, hj, hij⟩ := h1
  have hj' : j ∈ s := Finset.mem_of_mem_erase hj
  have hji : j ≠ i := Finset.ne_of_mem_erase hj
  have h2 : h i ∣ h j := hprime.dvd_of_dvd_pow hij
  rcases (hirr j hj').dvd_iff.mp h2 with hu | hassoc
  · exact (hirr i hi).not_isUnit hu
  · exact hji (hdist j hj' i hi (eq_of_monic_of_associated (hmon j hj') (hmon i hi) hassoc))

/-- **(Lemma "Norm criterion" over `F_p`, full statement.)**  Let
    `F = ∏_{i∈s} hᵢ^{μᵢ} ∈ F_p[Y]` with pairwise distinct monic irreducible `hᵢ` of degrees
    `mᵢ`.  Then `F` is a norm form `Orb_d(C)` over `F_{p^d}` (for some `C ≠ 0`) iff
    `d ∣ mᵢ μᵢ` for every `i`. -/
theorem normForm_iff_galoisField (hd : d ≠ 0) {ι : Type*} (s : Finset ι)
    (h : ι → (ZMod p)[X]) (μ : ι → ℕ) (hirr : ∀ i ∈ s, Irreducible (h i))
    (hmon : ∀ i ∈ s, (h i).Monic) (hdist : ∀ i ∈ s, ∀ j ∈ s, h i = h j → i = j) :
    (∃ Cp : (GaloisField p d)[X], Cp ≠ 0 ∧
        (∏ i ∈ s, h i ^ μ i).map (algebraMap (ZMod p) (GaloisField p d)) =
          Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d Cp) ↔
      ∀ i ∈ s, d ∣ (h i).natDegree * μ i := by
  constructor
  · rintro ⟨Cp, hC, hF⟩ i hi
    obtain ⟨h1, h2⟩ := exact_multiplicity_of_prod s h μ hirr hmon hdist hi
    exact dvd_natDegree_mul_galoisField p d hd hC hF (hirr i hi) (hmon i hi) h1 h2
  · intro hall
    classical
    choose! Cf hCf using fun i (hi : i ∈ s) =>
      pow_eq_orbProd_galoisField_of_dvd_mul p d hd (hirr i hi) (hmon i hi) (hall i hi)
    refine ⟨∏ i ∈ s, Cf i, (monic_prod_of_monic _ _ (fun i hi => (hCf i hi).1)).ne_zero, ?_⟩
    exact norm_form_of_factors _ _ s (fun i => h i ^ μ i) _ (fun i hi => (hCf i hi).2.2)

/-- The norm form `C` can be taken monic of degree `deg F / d = Σ mᵢ μᵢ / d`. -/
theorem normForm_of_dvd_galoisField (hd : d ≠ 0) {ι : Type*} (s : Finset ι)
    (h : ι → (ZMod p)[X]) (μ : ι → ℕ) (hirr : ∀ i ∈ s, Irreducible (h i))
    (hmon : ∀ i ∈ s, (h i).Monic) (hall : ∀ i ∈ s, d ∣ (h i).natDegree * μ i) :
    ∃ Cp : (GaloisField p d)[X], Cp.Monic ∧
      Cp.natDegree = ∑ i ∈ s, (h i).natDegree * μ i / d ∧
      (∏ i ∈ s, h i ^ μ i).map (algebraMap (ZMod p) (GaloisField p d)) =
        Galois.orbProd (act (frob : GaloisField p d ≃ₐ[ZMod p] GaloisField p d)) d Cp := by
  classical
  choose! Cf hCf using fun i (hi : i ∈ s) =>
    pow_eq_orbProd_galoisField_of_dvd_mul p d hd (hirr i hi) (hmon i hi) (hall i hi)
  refine ⟨∏ i ∈ s, Cf i, monic_prod_of_monic _ _ (fun i hi => (hCf i hi).1), ?_, ?_⟩
  · rw [natDegree_prod_of_monic _ _ (fun i hi => (hCf i hi).1)]
    exact Finset.sum_congr rfl (fun i hi => (hCf i hi).2.1)
  · exact norm_form_of_factors _ _ s (fun i => h i ^ μ i) _ (fun i hi => (hCf i hi).2.2)

end FullCriterion

end NormCriterion
